In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('drugs_for_common_treatments.csv')
df.head()

,drug_name,medical_condition,medical_condition_description,activity,rx_otc,pregnancy_category,csa,alcohol,rating,no_of_reviews,medical_condition_url,drug_link
0,doxycycline,Acne,Acne Other names: Acne Vulgaris; Blackheads; B...,87%,Rx,D,N,X,6.8,760.0,https://www.drugs.com/condition/acne.html,https://www.drugs.com/doxycycline.html
1,spironolactone,Acne,Acne Other names: Acne Vulgaris; Blackheads; B...,82%,Rx,C,N,X,7.2,449.0,https://www.drugs.com/condition/acne.html,https://www.drugs.com/spironolactone.html
2,minocycline,Acne,Acne Other names: Acne Vulgaris; Blackheads; B...,48%,Rx,D,N,NaN,5.7,482.0,https://www.drugs.com/condition/acne.html,https://www.drugs.com/minocycline.html
3,Accutane,Acne,Acne Other names: Acne Vulgaris; Blackheads; B...,41%,Rx,X,N,X,7.9,623.0,https://www.drugs.com/condition/acne.html,https://www.drugs.com/accutane.html
4,clindamycin,Acne,Acne Other names: Acne Vulgaris; Blackheads; B...,39%,Rx,B,N,NaN,7.4,146.0,https://www.drugs.com/condition/acne.html,https://www.drugs.com/mtm/clindamycin-topical....

In [ ]:
import pandas as pd

# Load CSV into DataFrame
df["rating"] = pd.to_numeric(df["rating"], errors="coerce")

# Sort by 'medical_condition' and 'rating' (descending)
df_sorted = df.sort_values(by=["medical_condition", "rating"], ascending=[True, False])

# Select top 7 drugs for each medical condition
top_drugs = (
    df_sorted.groupby("medical_condition")["drug_name"]
    .apply(lambda x: x.head(7).tolist())  # Get top 7 as a list
    .reset_index()
)

# Rename column to 'drugs'
top_drugs.rename(columns={"drug_name": "drugs"}, inplace=True)

# Display the new DataFrame
print(top_drugs)

# Save to a new CSV file
top_drugs.to_csv("top_7_drugs_per_condition.csv", index=False)

       medical_condition                                              drugs
0                   ADHD  [selegiline, ProCentra, Desoxyn, methamphetami...
1               AIDS/HIV  [Reyataz, Epzicom, atazanavir, Tivicay PD, Str...
2                   Acne  [Septra, Clindagel, erythromycin, Ery Pads, Ac...
3              Allergies  [hydroxyzine, corticotropin, Acthar, loratadin...
4            Alzheimer's  [Razadyne ER, Namzaric, donepezil / memantine,...
5                 Angina  [aspirin, Lopressor, Lovenox, Bayer Aspirin Ex...
6                Anxiety  [Alprazolam Intensol, Diazepam Intensol, Loree...
7                 Asthma  [Ipratropium Inhalation Solution, Xopenex, Atr...
8       Bipolar Disorder  [Lybalvi, tiagabine, olanzapine / samidorphan,...
9             Bronchitis  [Robafen, Septra, Cefzil, erythromycin, Mucine...
10                  COPD  [Rayos, Xopenex, revefenacin, Yupelri, Tudorza...
11                Cancer  [doxorubicin, vincristine, carboplatin, ifosfa...
12           Cholesterol  [Altoprev, FloLipid, Slo-Niacin, Lopid, Vytori...
13           Colds & Flu  [Promethazine DM, acetaminophen / dextromethor...
14          Constipation  [Citrucel, Fleet Bisacodyl, Citrate of Magnesi...
15              Covid 19  [ivermectin, Pfizer-BioNTech COVID-19 Vaccine,...
16            Depression  [Forfivo XL, Norpramin, amitriptyline / chlord...
17     Diabetes (Type 1)  [insulin aspart/insulin aspart protamine, Humu...
18     Diabetes (Type 2)  [insulin aspart/insulin aspart protamine, Glys...
19              Diarrhea  [Anti-Diarrheal, crofelemer, opium, bismuth su...
20                Eczema  [dexamethasone, Cloderm, Cordran Tape, flurand...
21  Erectile Dysfunction  [Caverject Impulse, Staxyn, Cialis, Viagra, ta...
22      GERD (Heartburn)  [Pepcid AC Chewable Tablets, Mylanta, Tagamet ...
23      Gastrointestinal  [Entereg, Lidocaine Viscous, alvimopan, lidoca...
24                  Gout  [probenecid, Aloprim, Zyloprim, Krystexxa, Ulo...
25             Hair Loss  [Kenalog-10, triamcinolone, Rogaine Women's, s...
26              Hayfever  [Aller-Tec, Allegra ODT, cyproheptadine, Zyrte...
27                Herpes  [Blistex Ointment, allantoin / camphor / pheno...
28          Hypertension  [bendroflumethiazide / nadolol, Aldactazide, b...
29        Hypothyroidism  [Westhroid, Thyquidity, Unithroid, Cytomel, Ti...
30           IBD (Bowel)  [Delzicol, Apriso, Asacol, Pentasa, Entocort E...
31          Incontinence  [Oxytrol, hyoscyamine, amitriptyline, trospium...
32              Insomnia  [pentobarbital, amobarbital, Nighttime Sleepai...
33             Menopause  [esterified estrogens / methyltestosterone, Bi...
34              Migraine  [Migergot, Goody's Extra Strength, acetaminoph...
35        Osteoarthritis  [Medrol Dosepak, Motrin, Depo-Medrol, Dolobid,...
36          Osteoporosis  [Premarin, conjugated estrogens, calcium / vit...
37                  Pain  [Buprenex, Feverall, Motrin IB, Vitapap, Anapr...
38             Pneumonia  [Zyvox, linezolid, Avelox I.V., Cefzil, tetrac...
39             Psoriasis  [Temovate, Neoral, Kenalog-10, ammonium lactat...
40  Rheumatoid Arthritis  [Azulfidine, ibuprofen, aspirin, Advil, Motrin...
41         Schizophrenia  [thiothixene, thioridazine, chlorpromazine, Cl...
42              Seizures  [Oxtellar XR, Qudexy XR, Xcopri, progesterone,...
43                Stroke  [nimodipine, aspirin, clopidogrel, Plavix, Act...
44             Swine Flu  [Relenza, zanamivir, Tamiflu, oseltamivir, per...
45                   UTI  [Amoxil, Vibramycin, ampicillin, Suprax, cefad...
46           Weight Loss  [Desoxyn, methamphetamine, amphetamine, Pregny...

In [22]:
%pip install FPDF

Collecting FPDF
  Downloading fpdf-1.7.2.tar.gz (39 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: FPDF
  Building wheel for FPDF (setup.py) ... done
  Created wheel for FPDF: filename=fpdf-1.7.2-py2.py3-none-any.whl size=40704 sha256=3d46e569e460cb5cab4dbe95dc9d772bb93cd0c9acc80fdbd5b8b3f432bf378f
  Stored in directory: /root/.cache/pip/wheels/65/4f/66/bbda9866da446a72e206d6484cd97381cbc7859a7068541c36
Successfully built FPDF
Installing collected packages: FPDF
Successfully installed FPDF-1.7.2

In [23]:
import pandas as pd
from fpdf import FPDF

def convert_csv_to_pdf(csv_path, pdf_path):
    # Load CSV into Pandas DataFrame
    df = pd.read_csv(csv_path)

    # Ensure 'drugs' column is properly formatted
    df["drugs"] = df["drugs"].apply(lambda x: eval(x) if isinstance(x, str) else x)

    # Initialize PDF
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    # Title
    pdf.set_font("Arial", style="B", size=16)
    pdf.cell(200, 10, "Medical Conditions and Their Treatments", ln=True, align="C")
    pdf.ln(10)  # Line break

    # Convert each row to a formatted sentence in the PDF
    pdf.set_font("Arial", size=12)
    for _, row in df.iterrows():
        condition = row["medical_condition"]
        drugs = ", ".join(row["drugs"])  # Convert list to comma-separated string
        text = f"{condition} can be cured by the following drugs: {drugs}."

        # Add text to PDF
        pdf.multi_cell(0, 10, text)
        pdf.ln(5)  # Extra space between records

    # Save PDF
    pdf.output(pdf_path)
    print(f"PDF saved successfully at: {pdf_path}")

# Example usage
csv_path = "/content/top_7_drugs_per_condition.csv"  # Replace with your CSV file path
pdf_path = "/content/medical_conditions.pdf"  # Output PDF file path
convert_csv_to_pdf(csv_path, pdf_path)

PDF saved successfully at: /content/medical_conditions.pdf

In [ ]:
df = df.dropna(subset=['rating'])
df['rating'] = pd.to_numeric(df['rating']) #converting string to numeric for sorting
df_sorted = df.sort_values(by=['medical_condition','rating'],ascending = [True,False])
top_drugs_df = df_sorted.groupby('medical_condition').head(7)
final_df = top_drugs_df[['medical_condition','drug_name']]
final_df.head(24)

<ipython-input-2-be943c2aadb1>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating'] = pd.to_numeric(df['rating']) #converting string to numeric for sorting

    medical_condition                                          drug_name
276              ADHD                                         selegiline
275              ADHD                                          ProCentra
260              ADHD                                            Desoxyn
270              ADHD                                    methamphetamine
247              ADHD                                          Jornay PM
253              ADHD                                          Dexedrine
273              ADHD                                        Methylin ER
312          AIDS/HIV                                            Reyataz
313          AIDS/HIV                                            Epzicom
336          AIDS/HIV                                         atazanavir
353          AIDS/HIV                                         Tivicay PD
297          AIDS/HIV                                           Stribild
307          AIDS/HIV  cobicistat / elvitegravir / emtricitabine / te...
356          AIDS/HIV                                          Delstrigo
18               Acne                                             Septra
37               Acne                                          Clindagel
39               Acne                                       erythromycin
67               Acne                                           Ery Pads
77               Acne                                              Acnex
81               Acne                                              Avita
85               Acne                          benzoyl peroxide / sulfur
402         Allergies                                        hydroxyzine
407         Allergies                                      corticotropin
408         Allergies                                             Acthar

In [21]:
num_records = len(top_drugs)
print(num_records)

47

In [20]:
top_drugs.head()

  medical_condition                                              drugs
0              ADHD  [selegiline, ProCentra, Desoxyn, methamphetami...
1          AIDS/HIV  [Reyataz, Epzicom, atazanavir, Tivicay PD, Str...
2              Acne  [Septra, Clindagel, erythromycin, Ery Pads, Ac...
3         Allergies  [hydroxyzine, corticotropin, Acthar, loratadin...
4       Alzheimer's  [Razadyne ER, Namzaric, donepezil / memantine,...

In [ ]:
import os
from google.colab import userdata
os.environ['GROQ_API_KEY'] = userdata.get('groq_api')
os.environ['LLAMA_CLOUD_API_KEY'] = userdata.get('llama_index_api')

In [ ]:
%pip install pypdf2 pydantic-ai langchain-groq langchain_experimental langchain-cohere langchain-community langchain_neo4j langchain langchain_google_genai neo4j

Collecting pypdf2
  Downloading pypdf2-3.0.1-py3-none-any.whl.metadata (6.8 kB)
Collecting pydantic-ai
  Downloading pydantic_ai-0.0.22-py3-none-any.whl.metadata (11 kB)
Collecting langchain-groq
  Downloading langchain_groq-0.2.4-py3-none-any.whl.metadata (3.0 kB)
Collecting langchain_experimental
  Downloading langchain_experimental-0.3.4-py3-none-any.whl.metadata (1.7 kB)
Collecting langchain-cohere
  Downloading langchain_cohere-0.4.2-py3-none-any.whl.metadata (6.6 kB)
Collecting langchain-community
  Downloading langchain_community-0.3.16-py3-none-any.whl.metadata (2.9 kB)
Collecting langchain_neo4j
  Downloading langchain_neo4j-0.3.0-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: langchain in /usr/local/lib/python3.11/dist-packages (0.3.16)
Collecting langchain_google_genai
  Downloading langchain_google_genai-2.0.9-py3-none-any.whl.metadata (3.6 kB)
Collecting neo4j
  Downloading neo4j-5.28.0-py3-none-any.whl.metadata (5.9 kB)
Collecting pydantic-ai-slim==0.0.22 (from pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai)
  Downloading pydantic_ai_slim-0.0.22-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: eval-type-backport>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from pydantic-ai-slim==0.0.22->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (0.2.2)
Collecting griffe>=1.3.2 (from pydantic-ai-slim==0.0.22->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai)
  Downloading griffe-1.5.6-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: httpx>=0.27 in /usr/local/lib/python3.11/dist-packages (from pydantic-ai-slim==0.0.22->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (0.28.1)
Collecting logfire-api>=1.2.0 (from pydantic-ai-slim==0.0.22->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai)
  Downloading logfire_api-3.5.2-py3-none-any.whl.metadata (971 bytes)
Collecting pydantic-graph==0.0.22 (from pydantic-ai-slim==0.0.22->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai)
  Downloading pydantic_graph-0.0.22-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: pydantic>=2.10 in /usr/local/lib/python3.11/dist-packages (from pydantic-ai-slim==0.0.22->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (2.10.6)
WARNING: pydantic-ai-slim 0.0.22 does not provide the extra 'graph'
Collecting anthropic>=0.40.0 (from pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai)
  Downloading anthropic-0.45.2-py3-none-any.whl.metadata (23 kB)
Collecting cohere>=5.13.11 (from pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai)
  Downloading cohere-5.13.11-py3-none-any.whl.metadata (3.4 kB)
Collecting groq>=0.12.0 (from pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai)
  Downloading groq-0.18.0-py3-none-any.whl.metadata (14 kB)
Collecting mistralai>=1.2.5 (from pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai)
  Downloading mistralai-1.5.0-py3-none-any.whl.metadata (29 kB)
Requirement already satisfied: openai>=1.59.0 in /usr/local/lib/python3.11/dist-packages (from pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (1.59.9)
Collecting google-auth>=2.36.0 (from pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai)
  Downloading google_auth-2.38.0-py2.py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: requests>=2.32.3 in /usr/local/lib/python3.11/dist-packages (from pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (2.32.3)
Collecting langchain-core<0.4.0,>=0.3.33 (from langchain-groq)
  Downloading langchain_core-0.3.33-py3-none-any.whl.metadata (6.3 kB)
Collecting types-pyyaml<7.0.0.0,>=6.0.12.20240917 (from langchain-cohere)
  Downloading types_PyYAML-6.0.12.20241230-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.11/dist-packages (from langchain-community) (6.0.2)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.11/dist-packages (from langchain-community) (2.0.37)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.11/dist-packages (from langchain-community) (3.11.11)
Collecting dataclasses-json<0.7,>=0.5.7 (from langchain-community)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting httpx-sse<0.5.0,>=0.4.0 (from langchain-community)
  Downloading httpx_sse-0.4.0-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: langsmith<0.4,>=0.1.125 in /usr/local/lib/python3.11/dist-packages (from langchain-community) (0.3.2)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.11/dist-packages (from langchain-community) (1.26.4)
Collecting pydantic-settings<3.0.0,>=2.4.0 (from langchain-community)
  Downloading pydantic_settings-2.7.1-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: tenacity!=8.4.0,<10,>=8.1.0 in /usr/local/lib/python3.11/dist-packages (from langchain-community) (9.0.0)
Requirement already satisfied: langchain-text-splitters<0.4.0,>=0.3.3 in /usr/local/lib/python3.11/dist-packages (from langchain) (0.3.5)
Collecting filetype<2.0.0,>=1.2.0 (from langchain_google_genai)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: google-generativeai<0.9.0,>=0.8.0 in /usr/local/lib/python3.11/dist-packages (from langchain_google_genai) (0.8.4)
Requirement already satisfied: pytz in /usr/local/lib/python3.11/dist-packages (from neo4j) (2024.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.18.3)
Collecting fastavro<2.0.0,>=1.9.4 (from cohere>=5.13.11->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai)
  Downloading fastavro-1.10.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.5 kB)
Requirement already satisfied: pydantic-core<3.0.0,>=2.18.2 in /usr/local/lib/python3.11/dist-packages (from cohere>=5.13.11->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (2.27.2)
Requirement already satisfied: tokenizers<1,>=0.15 in /usr/local/lib/python3.11/dist-packages (from cohere>=5.13.11->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (0.21.0)
Collecting types-requests<3.0.0,>=2.0.0 (from cohere>=5.13.11->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai)
  Downloading types_requests-2.32.0.20241016-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: typing_extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from cohere>=5.13.11->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (4.12.2)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7,>=0.5.7->langchain-community)
  Downloading marshmallow-3.26.1-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7,>=0.5.7->langchain-community)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: google-ai-generativelanguage==0.6.15 in /usr/local/lib/python3.11/dist-packages (from google-generativeai<0.9.0,>=0.8.0->langchain_google_genai) (0.6.15)
Requirement already satisfied: google-api-core in /usr/local/lib/python3.11/dist-packages (from google-generativeai<0.9.0,>=0.8.0->langchain_google_genai) (2.19.2)
Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.11/dist-packages (from google-generativeai<0.9.0,>=0.8.0->langchain_google_genai) (2.155.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from google-generativeai<0.9.0,>=0.8.0->langchain_google_genai) (4.25.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from google-generativeai<0.9.0,>=0.8.0->langchain_google_genai) (4.67.1)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /usr/local/lib/python3.11/dist-packages (from google-ai-generativelanguage==0.6.15->google-generativeai<0.9.0,>=0.8.0->langchain_google_genai) (1.26.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from groq>=0.12.0->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (3.7.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from groq>=0.12.0->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (1.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from groq>=0.12.0->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (1.3.1)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.11/dist-packages (from langchain-core<0.4.0,>=0.3.33->langchain-groq) (1.33)
Requirement already satisfied: packaging<25,>=23.2 in /usr/local/lib/python3.11/dist-packages (from langchain-core<0.4.0,>=0.3.33->langchain-groq) (24.2)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.125->langchain-community) (3.10.15)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: zstandard<0.24.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from langsmith<0.4,>=0.1.125->langchain-community) (0.23.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.10->pydantic-ai-slim==0.0.22->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (0.7.0)
Collecting python-dotenv>=0.21.0 (from pydantic-settings<3.0.0,>=2.4.0->langchain-community)
  Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.3->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.3->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.3->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.3->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (2024.12.14)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy<3,>=1.4->langchain-community) (3.1.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from anthropic>=0.40.0->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (0.8.2)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core->google-generativeai<0.9.0,>=0.8.0->langchain_google_genai) (1.66.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth>=2.36.0->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (5.5.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth>=2.36.0->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (0.4.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth>=2.36.0->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (4.9)
Collecting colorama>=0.4 (from griffe>=1.3.2->pydantic-ai-slim==0.0.22->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27->pydantic-ai-slim==0.0.22->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx>=0.27->pydantic-ai-slim==0.0.22->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (0.14.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.11/dist-packages (from jsonpatch<2.0,>=1.33->langchain-core<0.4.0,>=0.3.33->langchain-groq) (3.0.0)
Collecting jsonpath-python>=1.0.6 (from mistralai>=1.2.5->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai)
  Downloading jsonpath_python-1.0.6-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from mistralai>=1.2.5->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (2.8.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /usr/local/lib/python3.11/dist-packages (from tokenizers<1,>=0.15->cohere>=5.13.11->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (0.27.1)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain-community)
  Downloading mypy_extensions-1.0.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: httplib2<1.dev0,>=0.19.0 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client->google-generativeai<0.9.0,>=0.8.0->langchain_google_genai) (0.22.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client->google-generativeai<0.9.0,>=0.8.0->langchain_google_genai) (0.2.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client->google-generativeai<0.9.0,>=0.8.0->langchain_google_genai) (4.1.1)
Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai<0.9.0,>=0.8.0->langchain_google_genai) (1.70.0)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai<0.9.0,>=0.8.0->langchain_google_genai) (1.62.3)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /usr/local/lib/python3.11/dist-packages (from httplib2<1.dev0,>=0.19.0->google-api-python-client->google-generativeai<0.9.0,>=0.8.0->langchain_google_genai) (3.2.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers<1,>=0.15->cohere>=5.13.11->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers<1,>=0.15->cohere>=5.13.11->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (2024.10.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.36.0->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (0.6.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->mistralai>=1.2.5->pydantic-ai-slim[anthropic,cohere,graph,groq,mistral,openai,vertexai]==0.0.22->pydantic-ai) (1.17.0)
Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 14.9 MB/s eta 0:00:00
Downloading pydantic_ai-0.0.22-py3-none-any.whl (9.8 kB)
Downloading pydantic_ai_slim-0.0.22-py3-none-any.whl (93 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.0/94.0 kB 5.7 MB/s eta 0:00:00
Downloading pydantic_graph-0.0.22-py3-none-any.whl (16 kB)
Downloading langchain_groq-0.2.4-py3-none-any.whl (14 kB)
Downloading langchain_experimental-0.3.4-py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.2/209.2 kB 17.4 MB/s eta 0:00:00
Downloading langchain_cohere-0.4.2-py3-none-any.whl (42 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 kB 3.5 MB/s eta 0:00:00
Downloading langchain_community-0.3.16-py3-none-any.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 60.7 MB/s eta 0:00:00
Downloading langchain_neo4j-0.3.0-py3-none-any.whl (38 kB)
Downloading langchain_google_genai-2.0.9-py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 3.5 MB/s eta 0:00:00
Downloading neo4j-5.28.0-py3-none-any.whl (311 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.9/311.9 kB 21.1 MB/s eta 0:00:00
Downloading cohere-5.13.11-py3-none-any.whl (252 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 252.5/252.5 kB 15.5 MB/s eta 0:00:00
Downloading httpx_sse-0.4.0-py3-none-any.whl (7.8 kB)
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading groq-0.18.0-py3-none-any.whl (121 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.9/121.9 kB 9.4 MB/s eta 0:00:00
Downloading langchain_core-0.3.33-py3-none-any.whl (412 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 412.7/412.7 kB 25.6 MB/s eta 0:00:00
Downloading pydantic_settings-2.7.1-py3-none-any.whl (29 kB)
Downloading types_PyYAML-6.0.12.20241230-py3-none-any.whl (20 kB)
Downloading anthropic-0.45.2-py3-none-any.whl (222 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 222.8/222.8 kB 15.9 MB/s eta 0:00:00
Downloading fastavro-1.10.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 68.3 MB/s eta 0:00:00

In [ ]:
%pip install llama-index-llms-groq llama-index-embeddings-huggingface llama-index groq llama-index-graph-stores-kuzu

Collecting llama-index-llms-groq
  Downloading llama_index_llms_groq-0.3.1-py3-none-any.whl.metadata (2.3 kB)
Collecting llama-index-embeddings-huggingface
  Downloading llama_index_embeddings_huggingface-0.5.1-py3-none-any.whl.metadata (767 bytes)
Collecting llama-index
  Downloading llama_index-0.12.16-py3-none-any.whl.metadata (12 kB)
Collecting groq
  Downloading groq-0.18.0-py3-none-any.whl.metadata (14 kB)
Collecting llama-index-graph-stores-kuzu
  Downloading llama_index_graph_stores_kuzu-0.6.0-py3-none-any.whl.metadata (689 bytes)
Collecting llama-index-core<0.13.0,>=0.12.0 (from llama-index-llms-groq)
  Downloading llama_index_core-0.12.16.post1-py3-none-any.whl.metadata (2.5 kB)
Collecting llama-index-llms-openai-like<0.4.0,>=0.3.1 (from llama-index-llms-groq)
  Downloading llama_index_llms_openai_like-0.3.3-py3-none-any.whl.metadata (751 bytes)
Requirement already satisfied: huggingface-hub>=0.19.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (0.28.1)
Requirement already satisfied: sentence-transformers>=2.6.1 in /usr/local/lib/python3.11/dist-packages (from llama-index-embeddings-huggingface) (3.4.1)
Collecting llama-index-agent-openai<0.5.0,>=0.4.0 (from llama-index)
  Downloading llama_index_agent_openai-0.4.5-py3-none-any.whl.metadata (727 bytes)
Collecting llama-index-cli<0.5.0,>=0.4.0 (from llama-index)
  Downloading llama_index_cli-0.4.0-py3-none-any.whl.metadata (1.5 kB)
Collecting llama-index-embeddings-openai<0.4.0,>=0.3.0 (from llama-index)
  Downloading llama_index_embeddings_openai-0.3.1-py3-none-any.whl.metadata (684 bytes)
Collecting llama-index-indices-managed-llama-cloud>=0.4.0 (from llama-index)
  Downloading llama_index_indices_managed_llama_cloud-0.6.4-py3-none-any.whl.metadata (3.6 kB)
Collecting llama-index-llms-openai<0.4.0,>=0.3.0 (from llama-index)
  Downloading llama_index_llms_openai-0.3.18-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-index-multi-modal-llms-openai<0.5.0,>=0.4.0 (from llama-index)
  Downloading llama_index_multi_modal_llms_openai-0.4.3-py3-none-any.whl.metadata (726 bytes)
Collecting llama-index-program-openai<0.4.0,>=0.3.0 (from llama-index)
  Downloading llama_index_program_openai-0.3.1-py3-none-any.whl.metadata (764 bytes)
Collecting llama-index-question-gen-openai<0.4.0,>=0.3.0 (from llama-index)
  Downloading llama_index_question_gen_openai-0.3.0-py3-none-any.whl.metadata (783 bytes)
Collecting llama-index-readers-file<0.5.0,>=0.4.0 (from llama-index)
  Downloading llama_index_readers_file-0.4.4-py3-none-any.whl.metadata (5.4 kB)
Collecting llama-index-readers-llama-parse>=0.4.0 (from llama-index)
  Downloading llama_index_readers_llama_parse-0.4.0-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: nltk>3.8.1 in /usr/local/lib/python3.11/dist-packages (from llama-index) (3.9.1)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from groq) (3.7.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from groq) (2.10.6)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.10 in /usr/local/lib/python3.11/dist-packages (from groq) (4.12.2)
Collecting kuzu<0.8.0,>=0.7.0 (from llama-index-graph-stores-kuzu)
  Downloading kuzu-0.7.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.7 kB)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.5.0->groq) (3.10)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->groq) (2025.1.31)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->groq) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.14.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2024.10.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (4.67.1)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (3.11.11)
Requirement already satisfied: openai>=1.14.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-agent-openai<0.5.0,>=0.4.0->llama-index) (1.61.1)
Requirement already satisfied: SQLAlchemy>=1.4.49 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy[asyncio]>=1.4.49->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (2.0.37)
Collecting dataclasses-json (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: deprecated>=1.2.9.3 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (1.2.18)
Collecting dirtyjson<2.0.0,>=1.0.8 (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq)
  Downloading dirtyjson-1.0.8-py3-none-any.whl.metadata (11 kB)
Collecting filetype<2.0.0,>=1.2.0 (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: nest-asyncio<2.0.0,>=1.5.8 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (1.6.0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (3.4.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (1.26.4)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (11.1.0)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.2.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (9.0.0)
Collecting tiktoken>=0.3.3 (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq)
  Downloading tiktoken-0.8.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting typing-inspect>=0.8.0 (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (1.17.2)
Collecting llama-cloud<0.2.0,>=0.1.8 (from llama-index-indices-managed-llama-cloud>=0.4.0->llama-index)
  Downloading llama_cloud-0.1.12-py3-none-any.whl.metadata (851 bytes)
Requirement already satisfied: transformers<5.0.0,>=4.37.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-llms-openai-like<0.4.0,>=0.3.1->llama-index-llms-groq) (4.48.2)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.12.3 in /usr/local/lib/python3.11/dist-packages (from llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (4.13.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (2.2.2)
Collecting pypdf<6.0.0,>=5.1.0 (from llama-index-readers-file<0.5.0,>=0.4.0->llama-index)
  Downloading pypdf-5.2.0-py3-none-any.whl.metadata (7.2 kB)
Collecting striprtf<0.0.27,>=0.0.26 (from llama-index-readers-file<0.5.0,>=0.4.0->llama-index)
  Downloading striprtf-0.0.26-py3-none-any.whl.metadata (2.1 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.6.0-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index) (8.1.8)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index) (2024.11.6)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->groq) (2.27.2)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (2.5.1+cu124)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.13.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.18.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4<5.0.0,>=4.12.3->llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (2.6)
Collecting llama-cloud-services (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_cloud_services-0.6.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai>=1.14.0->llama-index-agent-openai<0.5.0,>=0.4.0->llama-index) (0.8.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2.3.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy>=1.4.49->SQLAlchemy[asyncio]>=1.4.49->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (3.1.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (3.1.5)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.3.0)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.37.0->llama-index-llms-openai-like<0.4.0,>=0.3.1->llama-index-llms-groq) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.37.0->llama-index-llms-openai-like<0.4.0,>=0.3.1->llama-index-llms-groq) (0.5.2)
Collecting mypy-extensions>=0.3.0 (from typing-inspect>=0.8.0->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq)
  Downloading mypy_extensions-1.0.0-py3-none-any.whl.metadata (1.1 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq)
  Downloading marshmallow-3.26.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (2025.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (3.0.2)
Collecting python-dotenv<2.0.0,>=1.0.1 (from llama-cloud-services->llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Downloading llama_index_llms_groq-0.3.1-py3-none-any.whl (2.9 kB)
Downloading llama_index_embeddings_huggingface-0.5.1-py3-none-any.whl (8.9 kB)
Downloading llama_index-0.12.16-py3-none-any.whl (6.9 kB)
Downloading groq-0.18.0-py3-none-any.whl (121 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.9/121.9 kB 6.3 MB/s eta 0:00:00
Downloading llama_index_graph_stores_kuzu-0.6.0-py3-none-any.whl (10 kB)
Downloading kuzu-0.7.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 14.1 MB/s eta 0:00:00
Downloading llama_index_agent_openai-0.4.5-py3-none-any.whl (13 kB)
Downloading llama_index_cli-0.4.0-py3-none-any.whl (27 kB)
Downloading llama_index_core-0.12.16.post1-py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 56.0 MB/s eta 0:00:00
Downloading llama_index_embeddings_openai-0.3.1-py3-none-any.whl (6.2 kB)
Downloading llama_index_indices_managed_llama_cloud-0.6.4-py3-none-any.whl (13 kB)
Downloading llama_index_llms_openai-0.3.18-py3-none-any.whl (14 kB)
Downloading llama_index_llms_openai_like-0.3.3-py3-none-any.whl (3.1 kB)
Downloading llama_index_multi_modal_llms_openai-0.4.3-py3-none-any.whl (5.9 kB)
Downloading llama_index_program_openai-0.3.1-py3-none-any.whl (5.3 kB)
Downloading llama_index_question_gen_openai-0.3.0-py3-none-any.whl (2.9 kB)
Downloading llama_index_readers_file-0.4.4-py3-none-any.whl (39 kB)
Downloading llama_index_readers_llama_parse-0.4.0-py3-none-any.whl (2.5 kB)
Downloading dirtyjson-1.0.8-py3-none-any.whl (25 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading llama_cloud-0.1.12-py3-none-any.whl (252 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.0/253.0 kB 18.7 MB/s eta 0:00:00

In [ ]:
from llama_index.core import SimpleDirectoryReader, KnowledgeGraphIndex,Document,Settings
from llama_index.core.graph_stores import SimpleGraphStore
from llama_index.core import StorageContext
from llama_index.llms.groq import Groq
from llama_index.llms.openai import OpenAI
from llama_index.core import Settings
from IPython.display import Markdown, display
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

In [ ]:
import kuzu

db = kuzu.Database("test1")

In [ ]:
from llama_index.graph_stores.kuzu import KuzuGraphStore

graph_store = KuzuGraphStore(db)
storage_context = StorageContext.from_defaults(graph_store=graph_store)

In [ ]:

csv_text = top_drugs.to_string(index=False)

# Create a list of Document objects
document = [Document(text=csv_text)]  # Wrap in a list

# Use HuggingFace's embedding model (change model_name if needed)
embedding_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")

# Set the embedding model
Settings.embed_model = embedding_model

# Initialize Groq LLM
llm = Groq(model="mixtral-8x7b-32768")  # Replace with the correct Groq model
Settings.llm = llm
Settings.chunk_size = 128


# Build the Knowledge Graph Index
index = KnowledgeGraphIndex.from_documents(
    documents=document,  # Ensure it's a list
    max_triplets_per_chunk=2,
    storage_context=storage_context,
)

In [ ]:
import pandas as pd
from llama_index.core import Settings, KnowledgeGraphIndex, Document, StorageContext
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.llms.groq import Groq

# Load CSV into Pandas DataFrame
csv_path = "/content/top_7_drugs_per_condition.csv"  # Replace with your actual file path
top_drugs = pd.read_csv(csv_path)

# Ensure 'drugs' column is properly formatted
top_drugs["drugs"] = top_drugs["drugs"].apply(lambda x: eval(x) if isinstance(x, str) else x)

# Convert DataFrame to formatted text
csv_text = "\n".join(
    f"{row['medical_condition']} can be cured by {', '.join(row['drugs'])}."
    for _, row in top_drugs.iterrows()
)

# Create a list of Document objects
documents = [Document(text=csv_text)]  # Wrap in a list

# Use HuggingFace's embedding model
embedding_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")

# Set embedding model
Settings.embed_model = embedding_model

# Initialize Groq LLM
llm = Groq(model="llama-3.3-70b-versatile")  # Replace with correct Groq model
Settings.llm = llm
Settings.chunk_size = 128

# Define storage context (use appropriate storage backend if needed)
storage_context = StorageContext.from_defaults()

# Build the Knowledge Graph Index
index = KnowledgeGraphIndex.from_documents(
    documents=documents,  # Ensure it's a list
    max_triplets_per_chunk=2,
    storage_context=storage_context,
)

In [19]:
from llama_index.graph_stores.kuzu import KuzuGraphStore
import networkx as nx

# Assuming `index` is your KnowledgeGraphIndex instance
# Convert the knowledge graph to a NetworkX graph
nx_graph = index.get_networkx_graph()

# Iterate over nodes
print("Nodes in the Knowledge Graph:")
for node in nx_graph.nodes(data=True):
    print(node)

# Iterate over edges
print("\nEdges in the Knowledge Graph:")
cnt=0
for edge in nx_graph.edges(data=True):
  cnt = cnt+1
  print(edge)

print(cnt)

Nodes in the Knowledge Graph:
('Adhd', {})
('Selegiline', {})
('Methamphetamine', {})
('Dexedrine', {})
('Desoxyn', {})
('Procentra', {})
('Jornay pm', {})
('Methylin er', {})
('Aids/hiv', {})
('Reyataz', {})
('Epzicom', {})
('Atazanavir', {})
('Tivicay pd', {})
('Stribild', {})
('Cobicistat / elvitegravir / emtricitabine / tenofovir', {})
('Delstrigo', {})

Edges in the Knowledge Graph:
('Adhd', 'Selegiline', {'label': 'Associated with', 'title': 'Associated with'})
('Adhd', 'Methamphetamine', {'label': 'Treated with', 'title': 'Treated with'})
('Adhd', 'Dexedrine', {'label': 'Can be cured by', 'title': 'Can be cured by'})
('Adhd', 'Desoxyn', {'label': 'Treated with', 'title': 'Treated with'})
('Adhd', 'Procentra', {'label': 'Associated with', 'title': 'Associated with'})
('Adhd', 'Jornay pm', {'label': 'Can be cured by', 'title': 'Can be cured by'})
('Adhd', 'Methylin er', {'label': 'Can be cured by', 'title': 'Can be cured by'})
('Aids/hiv', 'Reyataz', {'label': 'Treated with', 'title': 'Treated with'})
('Aids/hiv', 'Epzicom', {'label': 'Treated with', 'title': 'Treated with'})
('Aids/hiv', 'Atazanavir', {'label': 'Treated with', 'title': 'Treated with'})
('Aids/hiv', 'Tivicay pd', {'label': 'Can be cured by', 'title': 'Can be cured by'})
('Aids/hiv', 'Stribild', {'label': 'Can be cured by', 'title': 'Can be cured by'})
('Aids/hiv', 'Cobicistat / elvitegravir / emtricitabine / tenofovir', {'label': 'Can be cured by', 'title': 'Can be cured by'})
('Aids/hiv', 'Delstrigo', {'label': 'Can be cured by', 'title': 'Can be cured by'})
14

In [ ]:
import networkx as nx

# Assuming `index` is your KnowledgeGraphIndex instance
# Convert the knowledge graph to a NetworkX graph
nx_graph = index.get_networkx_graph()

# Write the NetworkX graph to a GraphML file
nx.write_graphml(nx_graph, "knowledge_graph_drugs.graphml")

print("Knowledge graph has been successfully exported to 'knowledge_graph.graphml'.")

Knowledge graph has been successfully exported to 'knowledge_graph.graphml'.

In [ ]:
import networkx as nx

# Read the GraphML file
graph = nx.read_graphml("knowledge_graph_drugs.graphml")

# Display the nodes
print("Nodes in the graph:")
for node in graph.nodes(data=True):
    print(node)

# Display the edges
print("\nEdges in the graph:")
for edge in graph.edges(data=True):
    print(edge)

Nodes in the graph:
('Desoxyn', {})
('Weight loss', {})
('Methamphetamine', {})
('Epzicom', {})
('Aids/hiv', {})
('Atazanavir', {})
('Hiv', {})
('Medication', {})
('Hiv treatment', {})
('Hiv medication', {})
('Medication for acne', {})
('Drug', {})
('Septra', {})
('Acne', {})
('Allergies', {})
('Acne medication', {})
('Bronchitis', {})
('Copd', {})
('Hydroxyzine', {})
('Adhd', {})
('Selegiline', {})
('Procentra', {})
('Reyataz', {})
('Pd', {})
('Aids/hiv medication', {})
('Benzoyl peroxide', {})
('Erythromycin', {})
('Benzoyl peroxide / sulfur', {})
('Treatment for', {})
('Colds & flu', {})
('Antibiotic', {})

Edges in the graph:
('Desoxyn', 'Weight loss', {'label': 'Is a drug for', 'title': 'Is a drug for'})
('Desoxyn', 'Methamphetamine', {'label': 'Is', 'title': 'Is'})
('Desoxyn', 'Adhd', {'label': 'Treated with', 'title': 'Treated with'})
('Weight loss', 'Methamphetamine', {'label': 'Is a drug for', 'title': 'Is a drug for'})
('Methamphetamine', 'Adhd', {'label': 'Treated with', 'title': 'Treated with'})
('Methamphetamine', 'Procentra', {'label': 'Is treatment for', 'title': 'Is treatment for'})
('Epzicom', 'Aids/hiv', {'label': 'Treated with', 'title': 'Treated with'})
('Epzicom', 'Atazanavir', {'label': 'Is', 'title': 'Is'})
('Epzicom', 'Hiv', {'label': 'Used to treat', 'title': 'Used to treat'})
('Epzicom', 'Medication', {'label': 'Is a type of', 'title': 'Is a type of'})
('Epzicom', 'Hiv treatment', {'label': 'Associated with', 'title': 'Associated with'})
('Epzicom', 'Hiv medication', {'label': 'Is', 'title': 'Is'})
('Epzicom', 'Medication for acne', {'label': 'Is', 'title': 'Is'})
('Epzicom', 'Drug', {'label': 'Is a', 'title': 'Is a'})
('Aids/hiv', 'Reyataz', {'label': 'Is treatment for', 'title': 'Is treatment for'})
('Aids/hiv', 'Atazanavir', {'label': 'Treated with', 'title': 'Treated with'})
('Atazanavir', 'Reyataz', {'label': 'Is a type of', 'title': 'Is a type of'})
('Atazanavir', 'Hiv', {'label': 'Treats', 'title': 'Treats'})
('Atazanavir', 'Medication', {'label': 'Is a', 'title': 'Is a'})
('Atazanavir', 'Medication for acne', {'label': 'Is', 'title': 'Is'})
('Hiv', 'Reyataz', {'label': 'Treats', 'title': 'Treats'})
('Medication', 'Septra', {'label': 'Is a', 'title': 'Is a'})
('Medication', 'Reyataz', {'label': 'Is a', 'title': 'Is a'})
('Medication', 'Erythromycin', {'label': 'Is', 'title': 'Is'})
('Drug', 'Septra', {'label': 'Is a', 'title': 'Is a'})
('Drug', 'Erythromycin', {'label': 'Is a', 'title': 'Is a'})
('Septra', 'Acne', {'label': 'Treated with', 'title': 'Treated with'})
('Septra', 'Allergies', {'label': 'Treats', 'title': 'Treats'})
('Septra', 'Acne medication', {'label': 'Is a', 'title': 'Is a'})
('Septra', 'Bronchitis', {'label': 'Treats', 'title': 'Treats'})
('Septra', 'Copd', {'label': 'Used to treat', 'title': 'Used to treat'})
('Acne', 'Benzoyl peroxide', {'label': 'Treated with', 'title': 'Treated with'})
('Acne', 'Erythromycin', {'label': 'Used to treat', 'title': 'Used to treat'})
('Acne', 'Benzoyl peroxide / sulfur', {'label': 'Associated with', 'title': 'Associated with'})
('Allergies', 'Hydroxyzine', {'label': 'Treated with', 'title': 'Treated with'})
('Allergies', 'Erythromycin', {'label': 'Treats', 'title': 'Treats'})
('Bronchitis', 'Erythromycin', {'label': 'Treats', 'title': 'Treats'})
('Copd', 'Erythromycin', {'label': 'Used to treat', 'title': 'Used to treat'})
('Adhd', 'Selegiline', {'label': 'Treated with', 'title': 'Treated with'})
('Adhd', 'Procentra', {'label': 'Treats', 'title': 'Treats'})
('Reyataz', 'Pd', {'label': 'Is a', 'title': 'Is a'})
('Reyataz', 'Aids/hiv medication', {'label': 'Is a', 'title': 'Is a'})
('Benzoyl peroxide', 'Treatment for', {'label': 'Is a', 'title': 'Is a'})
('Erythromycin', 'Colds & flu', {'label': 'Is used for', 'title': 'Is used for'})
('Erythromycin', 'Antibiotic', {'label': 'Is a type of', 'title': 'Is a type of'})

In [ ]:
import PyPDF2
from langchain_experimental.graph_transformers import LLMGraphTransformer
from langchain.docstore.document import Document
from langchain_groq import ChatGroq


# Initialize the LLM
llm = ChatGroq(
    model="mixtral-8x7b-32768",
    temperature=0,
    max_tokens=None,
    timeout=None,
    max_retries=2,
)

# Initialize the graph transformer
llm_transform = LLMGraphTransformer(llm=llm)

In [ ]:
documents = [Document(page_content="Sample text for testing.")]
graph_documents = llm_transform.convert_to_graph_documents(documents)
for graph in graph_documents:
    print(graph.nodes)
    print(graph.relationships)

[Node(id='Sample_Text', type='Text', properties={})]
[Relationship(source=Node(id='Sample_Text', type='Text', properties={}), target=Node(id='Entities', type='Group', properties={}), type='EXTRACTED_FROM', properties={}), Relationship(source=Node(id='Entities', type='Group', properties={}), target=Node(id='Nodes', type='Group', properties={}), type='CONTAINS', properties={}), Relationship(source=Node(id='Nodes', type='Group', properties={}), target=Node(id='Node_1', type='Entity', properties={}), type='MEMBER_OF', properties={}), Relationship(source=Node(id='Node_1', type='Entity', properties={}), target=Node(id='Properties', type='Group', properties={}), type='HAS_PROPERTIES', properties={}), Relationship(source=Node(id='Properties', type='Group', properties={}), target=Node(id='Property_1', type='Property', properties={}), type='HAS', properties={}), Relationship(source=Node(id='Property_1', type='Property', properties={}), target=Node(id='Property_Value_1', type='Value', properties={}), type='VALUE', properties={})]

In [ ]:
final_df.to_csv("top_7_drugs_per_condition.csv", index=False)

In [24]:
!pip install -U phidata

Collecting phidata
  Downloading phidata-2.7.10-py3-none-any.whl.metadata (38 kB)
Requirement already satisfied: docstring-parser in /usr/local/lib/python3.11/dist-packages (from phidata) (0.16)
Requirement already satisfied: gitpython in /usr/local/lib/python3.11/dist-packages (from phidata) (3.1.44)
Requirement already satisfied: httpx in /usr/local/lib/python3.11/dist-packages (from phidata) (0.28.1)
Requirement already satisfied: pydantic in /usr/local/lib/python3.11/dist-packages (from phidata) (2.10.6)
Collecting pydantic-settings (from phidata)
  Downloading pydantic_settings-2.7.1-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.11/dist-packages (from phidata) (1.0.1)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from phidata) (6.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from phidata) (13.9.4)
Collecting tomli (from phidata)
  Downloading tomli-2.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Requirement already satisfied: typer in /usr/local/lib/python3.11/dist-packages (from phidata) (0.15.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.11/dist-packages (from phidata) (4.12.2)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from gitpython->phidata) (4.0.12)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx->phidata) (3.7.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx->phidata) (2025.1.31)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx->phidata) (1.0.7)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from httpx->phidata) (3.10)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx->phidata) (0.14.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic->phidata) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic->phidata) (2.27.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->phidata) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->phidata) (2.18.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer->phidata) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer->phidata) (1.5.4)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from gitdb<5,>=4.0.1->gitpython->phidata) (5.0.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->phidata) (0.1.2)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx->phidata) (1.3.1)
Downloading phidata-2.7.10-py3-none-any.whl (716 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 716.9/716.9 kB 24.0 MB/s eta 0:00:00
Downloading pydantic_settings-2.7.1-py3-none-any.whl (29 kB)
Downloading tomli-2.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (236 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 236.0/236.0 kB 15.6 MB/s eta 0:00:00
Installing collected packages: tomli, pydantic-settings, phidata
Successfully installed phidata-2.7.10 pydantic-settings-2.7.1 tomli-2.2.1

In [25]:
%pip install lancedb tantivy pypdf sqlalchemy

Collecting lancedb
  Downloading lancedb-0.19.0-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (4.1 kB)
Collecting tantivy
  Downloading tantivy-0.22.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: pypdf in /usr/local/lib/python3.11/dist-packages (5.2.0)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.11/dist-packages (2.0.37)
Collecting deprecation (from lancedb)
  Downloading deprecation-2.1.0-py2.py3-none-any.whl.metadata (4.6 kB)
Collecting pylance==0.23.0 (from lancedb)
  Downloading pylance-0.23.0-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (7.2 kB)
Requirement already satisfied: tqdm>=4.27.0 in /usr/local/lib/python3.11/dist-packages (from lancedb) (4.67.1)
Requirement already satisfied: pydantic>=1.10 in /usr/local/lib/python3.11/dist-packages (from lancedb) (2.10.6)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from lancedb) (24.2)
Collecting overrides>=0.7 (from lancedb)
  Downloading overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: pyarrow>=14 in /usr/local/lib/python3.11/dist-packages (from pylance==0.23.0->lancedb) (17.0.0)
Requirement already satisfied: numpy>=1.22 in /usr/local/lib/python3.11/dist-packages (from pylance==0.23.0->lancedb) (1.26.4)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=1.10->lancedb) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=1.10->lancedb) (2.27.2)
Downloading lancedb-0.19.0-cp39-abi3-manylinux_2_28_x86_64.whl (32.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 32.3/32.3 MB 28.1 MB/s eta 0:00:00
Downloading pylance-0.23.0-cp39-abi3-manylinux_2_28_x86_64.whl (38.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.4/38.4 MB 19.4 MB/s eta 0:00:00
Downloading tantivy-0.22.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 78.6 MB/s eta 0:00:00
Downloading overrides-7.7.0-py3-none-any.whl (17 kB)
Downloading deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: tantivy, overrides, deprecation, pylance, lancedb
Successfully installed deprecation-2.1.0 lancedb-0.19.0 overrides-7.7.0 pylance-0.23.0 tantivy-0.22.0

In [64]:
%pip install -qU "langchain-community>=0.2.11" tavily-python

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.0/91.0 kB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 34.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 44.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 413.0/413.0 kB 25.3 MB/s eta 0:00:00

In [65]:
os.environ['TAVILY_API_KEY'] = userdata.get('tavily_api')

In [53]:
%pip install bs4 pgvector chromadb

Requirement already satisfied: bs4 in /usr/local/lib/python3.11/dist-packages (0.0.2)
Requirement already satisfied: pgvector in /usr/local/lib/python3.11/dist-packages (0.3.6)
Collecting chromadb
  Downloading chromadb-0.6.3-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from bs4) (4.13.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from pgvector) (1.26.4)
Collecting build>=1.0.3 (from chromadb)
  Downloading build-1.2.2.post1-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: pydantic>=1.9 in /usr/local/lib/python3.11/dist-packages (from chromadb) (2.10.6)
Collecting chroma-hnswlib==0.7.6 (from chromadb)
  Downloading chroma_hnswlib-0.7.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (252 bytes)
Collecting fastapi>=0.95.2 (from chromadb)
  Downloading fastapi-0.115.8-py3-none-any.whl.metadata (27 kB)
Collecting uvicorn>=0.18.3 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading uvicorn-0.34.0-py3-none-any.whl.metadata (6.5 kB)
Collecting posthog>=2.4.0 (from chromadb)
  Downloading posthog-3.11.0-py2.py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (4.12.2)
Collecting onnxruntime>=1.14.1 (from chromadb)
  Downloading onnxruntime-1.20.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (4.5 kB)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (1.16.0)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb)
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.30.0-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-instrumentation-fastapi>=0.41b0 (from chromadb)
  Downloading opentelemetry_instrumentation_fastapi-0.51b0-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (1.16.0)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.11/dist-packages (from chromadb) (0.21.0)
Collecting pypika>=0.48.9 (from chromadb)
  Downloading PyPika-0.48.9.tar.gz (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 kB 4.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (4.67.1)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.11/dist-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.11/dist-packages (from chromadb) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (1.70.0)
Collecting bcrypt>=4.0.1 (from chromadb)
  Downloading bcrypt-4.2.1-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (9.8 kB)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (0.15.1)
Collecting kubernetes>=28.1.0 (from chromadb)
  Downloading kubernetes-32.0.0-py2.py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.11/dist-packages (from chromadb) (9.0.0)
Requirement already satisfied: PyYAML>=6.0.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (6.0.2)
Collecting mmh3>=4.0.1 (from chromadb)
  Downloading mmh3-5.1.0-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (16 kB)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.11/dist-packages (from chromadb) (3.10.15)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: packaging>=19.1 in /usr/local/lib/python3.11/dist-packages (from build>=1.0.3->chromadb) (24.2)
Collecting pyproject_hooks (from build>=1.0.3->chromadb)
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Collecting starlette<0.46.0,>=0.40.0 (from fastapi>=0.95.2->chromadb)
  Downloading starlette-0.45.3-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27.0->chromadb) (3.7.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27.0->chromadb) (2025.1.31)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27.0->chromadb) (1.0.7)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27.0->chromadb) (3.10)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.14.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (2.8.2)
Requirement already satisfied: google-auth>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (2.27.0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (1.8.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (2.32.3)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: oauthlib>=3.2.2 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (3.2.2)
Requirement already satisfied: urllib3>=1.24.2 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (2.3.0)
Collecting durationpy>=0.7 (from kubernetes>=28.1.0->chromadb)
  Downloading durationpy-0.9-py3-none-any.whl.metadata (338 bytes)
Collecting coloredlogs (from onnxruntime>=1.14.1->chromadb)
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.11/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.1.24)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from onnxruntime>=1.14.1->chromadb) (4.25.6)
Requirement already satisfied: sympy in /usr/local/lib/python3.11/dist-packages (from onnxruntime>=1.14.1->chromadb) (1.13.1)
Requirement already satisfied: deprecated>=1.2.6 in /usr/local/lib/python3.11/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (1.2.18)
Requirement already satisfied: setuptools>=16.0 in /usr/local/lib/python3.11/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (75.1.0)
Requirement already satisfied: googleapis-common-protos~=1.52 in /usr/local/lib/python3.11/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.66.0)
Collecting opentelemetry-exporter-otlp-proto-common==1.30.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_exporter_otlp_proto_common-1.30.0-py3-none-any.whl.metadata (1.9 kB)
Collecting opentelemetry-proto==1.30.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_proto-1.30.0-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-sdk>=1.2.0 (from chromadb)
  Downloading opentelemetry_sdk-1.30.0-py3-none-any.whl.metadata (1.6 kB)
Collecting protobuf (from onnxruntime>=1.14.1->chromadb)
  Downloading protobuf-5.29.3-cp38-abi3-manylinux2014_x86_64.whl.metadata (592 bytes)
Collecting opentelemetry-instrumentation-asgi==0.51b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_instrumentation_asgi-0.51b0-py3-none-any.whl.metadata (2.1 kB)
Collecting opentelemetry-instrumentation==0.51b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_instrumentation-0.51b0-py3-none-any.whl.metadata (6.3 kB)
Collecting opentelemetry-semantic-conventions==0.51b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_semantic_conventions-0.51b0-py3-none-any.whl.metadata (2.5 kB)
Collecting opentelemetry-util-http==0.51b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_util_http-0.51b0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from opentelemetry-instrumentation==0.51b0->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb) (1.17.2)
Collecting asgiref~=3.0 (from opentelemetry-instrumentation-asgi==0.51b0->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading asgiref-3.8.1-py3-none-any.whl.metadata (9.3 kB)
Collecting opentelemetry-api>=1.2.0 (from chromadb)
  Downloading opentelemetry_api-1.30.0-py3-none-any.whl.metadata (1.6 kB)
Collecting importlib-metadata<=8.5.0,>=6.0 (from opentelemetry-api>=1.2.0->chromadb)
  Downloading importlib_metadata-8.5.0-py3-none-any.whl.metadata (4.8 kB)
Collecting monotonic>=1.5 (from posthog>=2.4.0->chromadb)
  Downloading monotonic-1.6-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting backoff>=1.10.0 (from posthog>=2.4.0->chromadb)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=1.9->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=1.9->chromadb) (2.27.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->chromadb) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->chromadb) (2.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /usr/local/lib/python3.11/dist-packages (from tokenizers>=0.13.2->chromadb) (0.28.1)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer>=0.9.0->chromadb) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Collecting httptools>=0.6.3 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading httptools-0.6.4-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.6 kB)
Requirement already satisfied: python-dotenv>=0.13 in /usr/local/lib/python3.11/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.0.1)
Collecting uvloop!=0.15.0,!=0.15.1,>=0.14.0 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading uvloop-0.21.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Collecting watchfiles>=0.13 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading watchfiles-1.0.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.11/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (14.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->bs4) (2.6)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (5.5.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (0.4.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (4.9)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2024.10.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib-metadata<=8.5.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->kubernetes>=28.1.0->chromadb) (3.4.1)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx>=0.27.0->chromadb) (1.3.1)
Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime>=1.14.1->chromadb)
  Downloading humanfriendly-10.0-py2.py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy->onnxruntime>=1.14.1->chromadb) (1.3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (0.6.1)
Downloading chromadb-0.6.3-py3-none-any.whl (611 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 611.1/611.1 kB 22.6 MB/s eta 0:00:00
Downloading chroma_hnswlib-0.7.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 64.2 MB/s eta 0:00:00
Downloading bcrypt-4.2.1-cp39-abi3-manylinux_2_28_x86_64.whl (278 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.6/278.6 kB 21.2 MB/s eta 0:00:00
Downloading build-1.2.2.post1-py3-none-any.whl (22 kB)
Downloading fastapi-0.115.8-py3-none-any.whl (94 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.8/94.8 kB 6.7 MB/s eta 0:00:00
Downloading kubernetes-32.0.0-py2.py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 67.4 MB/s eta 0:00:00
Downloading mmh3-5.1.0-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (101 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.6/101.6 kB 8.3 MB/s eta 0:00:00
Downloading onnxruntime-1.20.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (13.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 51.9 MB/s eta 0:00:00
Downloading opentelemetry_exporter_otlp_proto_grpc-1.30.0-py3-none-any.whl (18 kB)
Downloading opentelemetry_exporter_otlp_proto_common-1.30.0-py3-none-any.whl (18 kB)
Downloading opentelemetry_proto-1.30.0-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.9/55.9 kB 3.7 MB/s eta 0:00:00
Downloading opentelemetry_instrumentation_fastapi-0.51b0-py3-none-any.whl (12 kB)
Downloading opentelemetry_instrumentation-0.51b0-py3-none-any.whl (30 kB)
Downloading opentelemetry_instrumentation_asgi-0.51b0-py3-none-any.whl (16 kB)
Downloading opentelemetry_semantic_conventions-0.51b0-py3-none-any.whl (177 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.4/177.4 kB 12.0 MB/s eta 0:00:00
Downloading opentelemetry_api-1.30.0-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.0/65.0 kB 3.9 MB/s eta 0:00:00
Downloading opentelemetry_util_http-0.51b0-py3-none-any.whl (7.3 kB)
Downloading opentelemetry_sdk-1.30.0-py3-none-any.whl (118 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 9.4 MB/s eta 0:00:00
Downloading posthog-3.11.0-py2.py3-none-any.whl (72 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 4.6 MB/s eta 0:00:00
Downloading uvicorn-0.34.0-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 3.8 MB/s eta 0:00:00
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Downloading durationpy-0.9-py3-none-any.whl (3.5 kB)
Downloading httptools-0.6.4-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (459 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 459.8/459.8 kB 25.4 MB/s eta 0:00:00
Downloading importlib_metadata-8.5.0-py3-none-any.whl (26 kB)
Downloading monotonic-1.6-py2.py3-none-any.whl (8.2 kB)
Downloading protobuf-5.29.3-cp38-abi3-manylinux2014_x86_64.whl (319 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 319.7/319.7 kB 19.9 MB/s eta 0:00:00
Downloading starlette-0.45.3-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.5/71.5 kB 4.9 MB/s eta 0:00:00
Downloading uvloop-0.21.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 52.0 MB/s eta 0:00:00
Downloading watchfiles-1.0.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (452 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 452.6/452.6 kB 27.8 MB/s eta 0:00:00
Downloading coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 3.3 MB/s eta 0:00:00
Downloading pyproject_hooks-1.2.0-py3-none-any.whl (10 kB)
Downloading asgiref-3.8.1-py3-none-any.whl (23 kB)
Downloading humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 7.1 MB/s eta 0:00:00
Building wheels for collected packages: pypika
  Building wheel for pypika (pyproject.toml) ... done
  Created wheel for pypika: filename=PyPika-0.48.9-py2.py3-none-any.whl size=53771 sha256=acd0bbeaabae42b323c0168dc15bf036c768e2f22cd25757095c4083046fcec5
  Stored in directory: /root/.cache/pip/wheels/a3/01/bd/4c40ceb9d5354160cb186dcc153360f4ab7eb23e2b24daf96d
Successfully built pypika
Installing collected packages: pypika, monotonic, durationpy, uvloop, uvicorn, pyproject_hooks, protobuf, opentelemetry-util-http, mmh3, importlib-metadata, humanfriendly, httptools, chroma-hnswlib, bcrypt, backoff, asgiref, watchfiles, starlette, posthog, opentelemetry-proto, opentelemetry-api, coloredlogs, build, opentelemetry-semantic-conventions, opentelemetry-exporter-otlp-proto-common, onnxruntime, kubernetes, fastapi, opentelemetry-sdk, opentelemetry-instrumentation, opentelemetry-instrumentation-asgi, opentelemetry-exporter-otlp-proto-grpc, opentelemetry-instrumentation-fastapi, chromadb
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.25.6
    Uninstalling protobuf-4.25.6:
      Successfully uninstalled protobuf-4.25.6
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib_metadata 8.6.1
    Uninstalling importlib_metadata-8.6.1:
      Successfully uninstalled importlib_metadata-8.6.1
  Attempting uninstall: opentelemetry-api
    Found existing installation: opentelemetry-api 1.16.0
    Uninstalling opentelemetry-api-1.16.0:
      Successfully uninstalled opentelemetry-api-1.16.0
  Attempting uninstall: opentelemetry-semantic-conventions
    Found existing installation: opentelemetry-semantic-conventions 0.37b0
    Uninstalling opentelemetry-semantic-conventions-0.37b0:
      Successfully uninstalled opentelemetry-semantic-conventions-0.37b0
  Attempting uninstall: opentelemetry-sdk
    Found existing installation: opentelemetry-sdk 1.16.0
    Uninstalling opentelemetry-sdk-1.16.0:
      Successfully uninstalled opentelemetry-sdk-1.16.0

In [26]:
os.environ['GOOGLE_API_KEY'] = userdata.get('google_api')
os.environ['GEMINI_API_KEY'] = userdata.get('gemini_api')

In [61]:
from phi.knowledge.website import WebsiteKnowledgeBase
from phi.knowledge.pdf import PDFKnowledgeBase, PDFReader
from phi.vectordb.chroma import ChromaDb

"""knowledge_base = WebsiteKnowledgeBase(
    urls=["https://github.com/Prahmodh-Raj1/Personalized-Healthcare-Advisor/blob/main/Data/medical_conditions_and_drugs.pdf"],
    # Number of links to follow from the seed URLs
    max_links=10,
    # Table name: ai.website_documents
    vector_db=LanceDb(
        table_name="recipes",
        uri="tmp/lancedb",
        search_type=SearchType.vector,
        embedder=GeminiEmbedder(),
    ),
)
"""
knowledge_base = PDFKnowledgeBase(
    path="/content/medical_conditions.pdf",
    # Table name: ai.website_documents
    vector_db=LanceDb(
        table_name="recipes",
        uri="tmp/lancedb",
        search_type=SearchType.vector,
        embedder=GeminiEmbedder(),
    ),
)

'\nknowledge_base = PDFKnowledgeBase(\n    path="/content/medical_conditions.pdf",\n    # Table name: ai.website_documents\n    vector_db=LanceDb(\n        table_name="recipes",\n        uri="tmp/lancedb",\n        search_type=SearchType.vector,\n        embedder=GeminiEmbedder(),\n    ),\n)\n'

In [62]:
knowledge_base.load()

INFO     Loading knowledge base

INFO     Loaded 25 documents to knowledge base

In [66]:
from phi.tools.tavily import TavilyTools

agent = Agent(
    model=Gemini(id="gemini-2.0-flash"),
    tools=[TavilyTools()],
    # Add the knowledge base to the agent
    knowledge=knowledge_base,
    instructions=(
        "When answering queries about diseases, first check the knowledge base for drugs used to treat the condition. "
        "Then, use Tavily Search to fetch alerts about drug interactions, contraindications, and safety precautions for these drugs. "
        "Ensure that the response is well-structured, first listing the recommended drugs and then summarizing any relevant warnings or precautions. "
        "If the knowledge base lacks information, rely on Tavily Search to provide relevant drug details. "
        "Format the response clearly and concisely."
    ),
    show_tool_calls=True,
    markdown=True,
)

# Example query
agent.print_response("How can AIDS be cured?", stream=True)

Output()

In [40]:
from phi.agent import Agent
from phi.model.google import Gemini
from phi.embedder.openai import OpenAIEmbedder
from phi.knowledge.pdf import PDFUrlKnowledgeBase

from phi.vectordb.lancedb import LanceDb, SearchType
from phi.embedder.google import GeminiEmbedder

# Create a knowledge base from a PDF
knowledge_base = PDFUrlKnowledgeBase(
    urls=["https://medical-conditions-and-drugs.tiiny.site/"],
    # Use LanceDB as the vector database
    vector_db=LanceDb(
        table_name="recipes",
        uri="tmp/lancedb",
        search_type=SearchType.vector,
        embedder=GeminiEmbedder(),
    ),
)
# Comment out after first run as the knowledge base is loaded


agent = Agent(
    model=Gemini(id="gemini-2.0-flash"),
    # Add the knowledge base to the agent
    knowledge=knowledge_base,
    show_tool_calls=True,
    markdown=True,
)
agent.print_response("How do I cure", stream=True)

Output()

In [41]:
knowledge_base

PDFUrlKnowledgeBase(reader=PDFUrlReader(chunk=True, chunk_size=3000, separators=['\n', '\n\n', '\r', '\r\n', '\n\r', '\t', ' ', '  '], chunking_strategy=<phi.document.chunking.fixed.FixedSizeChunking object at 0x70b4c2608d10>), vector_db=<phi.vectordb.lancedb.lance_db.LanceDb object at 0x70b4ad7518d0>, num_documents=5, optimize_on=1000, driver='knowledge', chunking_strategy=<phi.document.chunking.fixed.FixedSizeChunking object at 0x70b4c2608d10>, urls=['https://medical-conditions-and-drugs.tiiny.site/'])