### Data Preprocessing and Formatting

In [ ]:
df = pd.read_csv('/content/symptoms.csv')
df.head()

,disease_tag,implicit_symptoms,explicit_symptoms
0,46,"{True: [60], False: []}","{True: array([20]), False: []}"
1,156,"{True: [134], False: []}","{True: array([337]), False: []}"
2,266,"{True: [203], False: []}","{True: array([219]), False: []}"
3,135,"{True: [58, 99, 140], False: []}","{True: array([17, 82, 50]), False: []}"
4,182,"{True: [225], False: []}","{True: array([291, 39]), False: []}"

In [ ]:
pdf = pd.read_csv('/content/disease_symptoms.csv')
pdf.head(30)

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal Infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal Infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal Infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal Infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal Infection
5,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal Infection
6,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal Infection
7,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal Infection
8,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal Infection
9,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal Infection
10,0,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
11,0,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
12,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
13,0,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
14,0,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
15,0,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
16,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
17,0,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
18,0,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
19,0,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
20,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,GERD
21,0,0,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,GERD
22,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,GERD
23,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,GERD
24,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,GERD
25,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,GERD
26,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,GERD
27,0,0,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,GERD
28,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,GERD
29,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,GERD

In [ ]:
import pandas as pd

# Load the dataset
file_path = "/content/disease_symptoms.csv"  # Replace with your actual CSV file path
df = pd.read_csv(file_path)

# Separate symptoms and prognosis columns
symptom_columns = df.columns[:-1]  # All columns except the last one (which is 'prognosis')
prognosis_column = df.columns[-1]  # The last column (disease name)

# Dictionary to store the new format
disease_symptoms = {}

# Iterate over each row
for _, row in df.iterrows():
    disease = row[prognosis_column]  # Extract disease name
    symptoms = [symptom for symptom in symptom_columns if row[symptom] == 1]  # Get symptoms with '1'

    # Append symptoms to the disease in dictionary
    if disease in disease_symptoms:
        disease_symptoms[disease].update(symptoms)  # Use a set to avoid duplicates
    else:
        disease_symptoms[disease] = set(symptoms)

# Convert dictionary to a DataFrame
formatted_data = pd.DataFrame({"Disease": disease_symptoms.keys(),
                               "Symptoms": [", ".join(symptoms) for symptoms in disease_symptoms.values()]})

# Save to CSV
output_file = "formatted_disease_symptoms.csv"
formatted_data.to_csv(output_file, index=False)

print(f"Transformed data saved to {output_file}")

Transformed data saved to formatted_disease_symptoms.csv

In [1]:
import pandas as pd
fd = pd.read_csv('formatted_disease_symptoms.csv')
fd.head()

               Disease                                           Symptoms
0     Fungal Infection  dischromic _patches, skin_rash, itching, nodal...
1              Allergy  watering_from_eyes, shivering, chills, continu...
2                 GERD  chest_pain, vomiting, ulcers_on_tongue, acidit...
3  Chronic Cholestasis  itching, vomiting, loss_of_appetite, yellowing...
4        Drug Reaction  skin_rash, itching, burning_micturition, spott...

### Construction of Knowledge Graph

In [2]:
%pip install llama-index groq chromadb

Collecting llama-index
  Downloading llama_index-0.12.15-py3-none-any.whl.metadata (12 kB)
Collecting groq
  Downloading groq-0.16.0-py3-none-any.whl.metadata (14 kB)
Collecting chromadb
  Downloading chromadb-0.6.3-py3-none-any.whl.metadata (6.8 kB)
Collecting llama-index-agent-openai<0.5.0,>=0.4.0 (from llama-index)
  Downloading llama_index_agent_openai-0.4.3-py3-none-any.whl.metadata (727 bytes)
Collecting llama-index-cli<0.5.0,>=0.4.0 (from llama-index)
  Downloading llama_index_cli-0.4.0-py3-none-any.whl.metadata (1.5 kB)
Collecting llama-index-core<0.13.0,>=0.12.15 (from llama-index)
  Downloading llama_index_core-0.12.15-py3-none-any.whl.metadata (2.5 kB)
Collecting llama-index-embeddings-openai<0.4.0,>=0.3.0 (from llama-index)
  Downloading llama_index_embeddings_openai-0.3.1-py3-none-any.whl.metadata (684 bytes)
Collecting llama-index-indices-managed-llama-cloud>=0.4.0 (from llama-index)
  Downloading llama_index_indices_managed_llama_cloud-0.6.4-py3-none-any.whl.metadata (3.6 kB)
Collecting llama-index-llms-openai<0.4.0,>=0.3.0 (from llama-index)
  Downloading llama_index_llms_openai-0.3.16-py3-none-any.whl.metadata (3.3 kB)
Collecting llama-index-multi-modal-llms-openai<0.5.0,>=0.4.0 (from llama-index)
  Downloading llama_index_multi_modal_llms_openai-0.4.3-py3-none-any.whl.metadata (726 bytes)
Collecting llama-index-program-openai<0.4.0,>=0.3.0 (from llama-index)
  Downloading llama_index_program_openai-0.3.1-py3-none-any.whl.metadata (764 bytes)
Collecting llama-index-question-gen-openai<0.4.0,>=0.3.0 (from llama-index)
  Downloading llama_index_question_gen_openai-0.3.0-py3-none-any.whl.metadata (783 bytes)
Collecting llama-index-readers-file<0.5.0,>=0.4.0 (from llama-index)
  Downloading llama_index_readers_file-0.4.4-py3-none-any.whl.metadata (5.4 kB)
Collecting llama-index-readers-llama-parse>=0.4.0 (from llama-index)
  Downloading llama_index_readers_llama_parse-0.4.0-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: nltk>3.8.1 in /usr/local/lib/python3.11/dist-packages (from llama-index) (3.9.1)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from groq) (3.7.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from groq) (2.10.6)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.10 in /usr/local/lib/python3.11/dist-packages (from groq) (4.12.2)
Collecting build>=1.0.3 (from chromadb)
  Downloading build-1.2.2.post1-py3-none-any.whl.metadata (6.5 kB)
Collecting chroma-hnswlib==0.7.6 (from chromadb)
  Downloading chroma_hnswlib-0.7.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (252 bytes)
Collecting fastapi>=0.95.2 (from chromadb)
  Downloading fastapi-0.115.8-py3-none-any.whl.metadata (27 kB)
Collecting uvicorn>=0.18.3 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading uvicorn-0.34.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: numpy>=1.22.5 in /usr/local/lib/python3.11/dist-packages (from chromadb) (1.26.4)
Collecting posthog>=2.4.0 (from chromadb)
  Downloading posthog-3.11.0-py2.py3-none-any.whl.metadata (2.9 kB)
Collecting onnxruntime>=1.14.1 (from chromadb)
  Downloading onnxruntime-1.20.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (4.5 kB)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (1.16.0)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb)
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.29.0-py3-none-any.whl.metadata (2.2 kB)
Collecting opentelemetry-instrumentation-fastapi>=0.41b0 (from chromadb)
  Downloading opentelemetry_instrumentation_fastapi-0.50b0-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (1.16.0)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.11/dist-packages (from chromadb) (0.21.0)
Collecting pypika>=0.48.9 (from chromadb)
  Downloading PyPika-0.48.9.tar.gz (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 kB 5.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (4.67.1)
Collecting overrides>=7.3.1 (from chromadb)
  Downloading overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.11/dist-packages (from chromadb) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (1.70.0)
Collecting bcrypt>=4.0.1 (from chromadb)
  Downloading bcrypt-4.2.1-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (9.8 kB)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (0.15.1)
Collecting kubernetes>=28.1.0 (from chromadb)
  Downloading kubernetes-32.0.0-py2.py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.11/dist-packages (from chromadb) (9.0.0)
Requirement already satisfied: PyYAML>=6.0.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (6.0.2)
Collecting mmh3>=4.0.1 (from chromadb)
  Downloading mmh3-5.1.0-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (16 kB)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.11/dist-packages (from chromadb) (3.10.15)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.5.0->groq) (3.10)
Requirement already satisfied: packaging>=19.1 in /usr/local/lib/python3.11/dist-packages (from build>=1.0.3->chromadb) (24.2)
Collecting pyproject_hooks (from build>=1.0.3->chromadb)
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Collecting starlette<0.46.0,>=0.40.0 (from fastapi>=0.95.2->chromadb)
  Downloading starlette-0.45.3-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->groq) (2024.12.14)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->groq) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.14.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (2.8.2)
Requirement already satisfied: google-auth>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (2.27.0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (1.8.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (2.32.3)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (1.3.1)
Requirement already satisfied: oauthlib>=3.2.2 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (3.2.2)
Requirement already satisfied: urllib3>=1.24.2 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (2.3.0)
Collecting durationpy>=0.7 (from kubernetes>=28.1.0->chromadb)
  Downloading durationpy-0.9-py3-none-any.whl.metadata (338 bytes)
Requirement already satisfied: openai>=1.14.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-agent-openai<0.5.0,>=0.4.0->llama-index) (1.59.9)
Requirement already satisfied: SQLAlchemy>=1.4.49 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy[asyncio]>=1.4.49->llama-index-core<0.13.0,>=0.12.15->llama-index) (2.0.37)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.6 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.15->llama-index) (3.11.11)
Collecting dataclasses-json (from llama-index-core<0.13.0,>=0.12.15->llama-index)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: deprecated>=1.2.9.3 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.15->llama-index) (1.2.18)
Collecting dirtyjson<2.0.0,>=1.0.8 (from llama-index-core<0.13.0,>=0.12.15->llama-index)
  Downloading dirtyjson-1.0.8-py3-none-any.whl.metadata (11 kB)
Collecting filetype<2.0.0,>=1.2.0 (from llama-index-core<0.13.0,>=0.12.15->llama-index)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.15->llama-index) (2024.10.0)
Requirement already satisfied: nest-asyncio<2.0.0,>=1.5.8 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.15->llama-index) (1.6.0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.15->llama-index) (3.4.2)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.15->llama-index) (11.1.0)
Collecting tiktoken>=0.3.3 (from llama-index-core<0.13.0,>=0.12.15->llama-index)
  Downloading tiktoken-0.8.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting typing-inspect>=0.8.0 (from llama-index-core<0.13.0,>=0.12.15->llama-index)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.15->llama-index) (1.17.2)
Collecting llama-cloud<0.2.0,>=0.1.8 (from llama-index-indices-managed-llama-cloud>=0.4.0->llama-index)
  Downloading llama_cloud-0.1.11-py3-none-any.whl.metadata (912 bytes)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.12.3 in /usr/local/lib/python3.11/dist-packages (from llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (4.12.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (2.2.2)
Collecting pypdf<6.0.0,>=5.1.0 (from llama-index-readers-file<0.5.0,>=0.4.0->llama-index)
  Downloading pypdf-5.2.0-py3-none-any.whl.metadata (7.2 kB)
Collecting striprtf<0.0.27,>=0.0.26 (from llama-index-readers-file<0.5.0,>=0.4.0->llama-index)
  Downloading striprtf-0.0.26-py3-none-any.whl.metadata (2.1 kB)
Collecting llama-parse>=0.5.0 (from llama-index-readers-llama-parse>=0.4.0->llama-index)
  Downloading llama_parse-0.5.20-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index) (8.1.8)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index) (2024.11.6)
Collecting coloredlogs (from onnxruntime>=1.14.1->chromadb)
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.11/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.1.24)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from onnxruntime>=1.14.1->chromadb) (4.25.6)
Requirement already satisfied: sympy in /usr/local/lib/python3.11/dist-packages (from onnxruntime>=1.14.1->chromadb) (1.13.1)
Requirement already satisfied: setuptools>=16.0 in /usr/local/lib/python3.11/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (75.1.0)
Requirement already satisfied: googleapis-common-protos~=1.52 in /usr/local/lib/python3.11/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.66.0)
Collecting opentelemetry-exporter-otlp-proto-common==1.29.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_exporter_otlp_proto_common-1.29.0-py3-none-any.whl.metadata (1.8 kB)
Collecting opentelemetry-proto==1.29.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_proto-1.29.0-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-sdk>=1.2.0 (from chromadb)
  Downloading opentelemetry_sdk-1.29.0-py3-none-any.whl.metadata (1.5 kB)
Collecting protobuf (from onnxruntime>=1.14.1->chromadb)
  Downloading protobuf-5.29.3-cp38-abi3-manylinux2014_x86_64.whl.metadata (592 bytes)
Collecting opentelemetry-instrumentation-asgi==0.50b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_instrumentation_asgi-0.50b0-py3-none-any.whl.metadata (1.9 kB)
Collecting opentelemetry-instrumentation==0.50b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_instrumentation-0.50b0-py3-none-any.whl.metadata (6.1 kB)
Collecting opentelemetry-semantic-conventions==0.50b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_semantic_conventions-0.50b0-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-util-http==0.50b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_util_http-0.50b0-py3-none-any.whl.metadata (2.5 kB)
Collecting asgiref~=3.0 (from opentelemetry-instrumentation-asgi==0.50b0->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading asgiref-3.8.1-py3-none-any.whl.metadata (9.3 kB)
Collecting opentelemetry-api>=1.2.0 (from chromadb)
  Downloading opentelemetry_api-1.29.0-py3-none-any.whl.metadata (1.4 kB)
Collecting importlib-metadata<=8.5.0,>=6.0 (from opentelemetry-api>=1.2.0->chromadb)
  Downloading importlib_metadata-8.5.0-py3-none-any.whl.metadata (4.8 kB)
Collecting monotonic>=1.5 (from posthog>=2.4.0->chromadb)
  Downloading monotonic-1.6-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting backoff>=1.10.0 (from posthog>=2.4.0->chromadb)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->groq) (2.27.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->chromadb) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->chromadb) (2.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /usr/local/lib/python3.11/dist-packages (from tokenizers>=0.13.2->chromadb) (0.27.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Collecting httptools>=0.6.3 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading httptools-0.6.4-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.6 kB)
Collecting python-dotenv>=0.13 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Collecting uvloop!=0.15.0,!=0.15.1,>=0.14.0 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading uvloop-0.21.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Collecting watchfiles>=0.13 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading watchfiles-1.0.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.11/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (14.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.15->llama-index) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.15->llama-index) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.15->llama-index) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.15->llama-index) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.15->llama-index) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.15->llama-index) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.15->llama-index) (1.18.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4<5.0.0,>=4.12.3->llama-index-readers-file<0.5.0,>=0.4.0->llama-index) (2.6)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (5.5.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (0.4.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (4.9)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.17.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib-metadata<=8.5.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai>=1.14.0->llama-index-agent-openai<0.5.0,>=0.4.0->llama-index) (0.8.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->kubernetes>=28.1.0->chromadb) (3.4.1)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy>=1.4.49->SQLAlchemy[asyncio]>=1.4.49->llama-index-core<0.13.0,>=0.12.15->llama-index) (3.1.1)
Collecting mypy-extensions>=0.3.0 (from typing-inspect>=0.8.0->llama-index-core<0.13.0,>=0.12.15->llama-index)
  Downloading mypy_extensions-1.0.0-py3-none-any.whl.metadata (1.1 kB)
Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime>=1.14.1->chromadb)
  Downloading humanfriendly-10.0-py2.py3-none-any.whl.metadata (9.2 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json->llama-index-core<0.13.0,>=0.12.15->llama-index)
  Downloading marshmallow-3.26.0-py3-none-any.whl.metadata (7.3 kB)

In [3]:
%pip install llama-index-llms-groq llama-index-embeddings-huggingface

Collecting llama-index-llms-groq
  Downloading llama_index_llms_groq-0.3.1-py3-none-any.whl.metadata (2.3 kB)
Collecting llama-index-embeddings-huggingface
  Downloading llama_index_embeddings_huggingface-0.5.1-py3-none-any.whl.metadata (767 bytes)
Requirement already satisfied: llama-index-core<0.13.0,>=0.12.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-llms-groq) (0.12.15)
Collecting llama-index-llms-openai-like<0.4.0,>=0.3.1 (from llama-index-llms-groq)
  Downloading llama_index_llms_openai_like-0.3.3-py3-none-any.whl.metadata (751 bytes)
Requirement already satisfied: huggingface-hub>=0.19.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (0.27.1)
Requirement already satisfied: sentence-transformers>=2.6.1 in /usr/local/lib/python3.11/dist-packages (from llama-index-embeddings-huggingface) (3.3.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2024.10.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (4.12.2)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (3.11.11)
Requirement already satisfied: SQLAlchemy>=1.4.49 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy[asyncio]>=1.4.49->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (2.0.37)
Requirement already satisfied: dataclasses-json in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (0.6.7)
Requirement already satisfied: deprecated>=1.2.9.3 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (1.2.18)
Requirement already satisfied: dirtyjson<2.0.0,>=1.0.8 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (1.0.8)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (1.2.0)
Requirement already satisfied: httpx in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (0.28.1)
Requirement already satisfied: nest-asyncio<2.0.0,>=1.5.8 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (1.6.0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (3.4.2)
Requirement already satisfied: nltk>3.8.1 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (1.26.4)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (11.1.0)
Requirement already satisfied: pydantic>=2.8.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (2.10.6)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.2.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (9.0.0)
Requirement already satisfied: tiktoken>=0.3.3 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (0.8.0)
Requirement already satisfied: typing-inspect>=0.8.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (0.9.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (1.17.2)
Requirement already satisfied: llama-index-llms-openai<0.4.0,>=0.3.9 in /usr/local/lib/python3.11/dist-packages (from llama-index-llms-openai-like<0.4.0,>=0.3.1->llama-index-llms-groq) (0.3.16)
Requirement already satisfied: transformers<5.0.0,>=4.37.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-llms-openai-like<0.4.0,>=0.3.1->llama-index-llms-groq) (4.47.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (2.5.1+cu124)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.13.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.18.3)
Requirement already satisfied: openai<2.0.0,>=1.58.1 in /usr/local/lib/python3.11/dist-packages (from llama-index-llms-openai<0.4.0,>=0.3.9->llama-index-llms-openai-like<0.4.0,>=0.3.1->llama-index-llms-groq) (1.59.9)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (8.1.8)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (2024.11.6)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.8.0->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.8.0->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (2.27.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2024.12.14)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy>=1.4.49->SQLAlchemy[asyncio]>=1.4.49->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (3.1.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (3.1.5)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.3.0)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.37.0->llama-index-llms-openai-like<0.4.0,>=0.3.1->llama-index-llms-groq) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.37.0->llama-index-llms-openai-like<0.4.0,>=0.3.1->llama-index-llms-groq) (0.5.2)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from typing-inspect>=0.8.0->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (1.0.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.11/dist-packages (from dataclasses-json->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (3.26.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (3.7.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx->llama-index-core<0.13.0,>=0.12.0->llama-index-llms-groq) (0.14.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (3.5.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from openai<2.0.0,>=1.58.1->llama-index-llms-openai<0.4.0,>=0.3.9->llama-index-llms-openai-like<0.4.0,>=0.3.1->llama-index-llms-groq) (1.9.0)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai<2.0.0,>=1.58.1->llama-index-llms-openai<0.4.0,>=0.3.9->llama-index-llms-openai-like<0.4.0,>=0.3.1->llama-index-llms-groq) (0.8.2)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from openai<2.0.0,>=1.58.1->llama-index-llms-openai<0.4.0,>=0.3.9->llama-index-llms-openai-like<0.4.0,>=0.3.1->llama-index-llms-groq) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (3.0.2)
Downloading llama_index_llms_groq-0.3.1-py3-none-any.whl (2.9 kB)
Downloading llama_index_embeddings_huggingface-0.5.1-py3-none-any.whl (8.9 kB)
Downloading llama_index_llms_openai_like-0.3.3-py3-none-any.whl (3.1 kB)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.7 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 83.2 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 74.4 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 47.2 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.9 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 6.2 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 11.4 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.7 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.8 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 57.9 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, llama-index-llms-openai-like, llama-index-llms-groq, llama-index-embeddings-huggingface
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83

In [4]:
import os
from google.colab import userdata
os.environ['GROQ_API_KEY'] = userdata.get('groq_api')
os.environ['LLAMA_CLOUD_API_KEY'] = userdata.get('llama_index_api')

In [16]:
from llama_index.core import SimpleDirectoryReader, KnowledgeGraphIndex,Document,Settings
from llama_index.core.graph_stores import SimpleGraphStore
from llama_index.core import StorageContext
from llama_index.llms.groq import Groq
from llama_index.llms.openai import OpenAI
from llama_index.core import Settings
from IPython.display import Markdown, display
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

In [ ]:
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.core import KnowledgeGraphIndex, Document, Settings
from llama_index.core.graph_stores import SimpleGraphStore
from llama_index.core import StorageContext
from llama_index.llms.groq import Groq

# Convert CSV to text format
csv_text = fd.to_string(index=False)

# Create a list of Document objects
document = [Document(text=csv_text)]  # Wrap in a list

# Use HuggingFace's embedding model (change model_name if needed)
embedding_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")

# Set the embedding model
Settings.embed_model = embedding_model

# Initialize Groq LLM
llm = Groq(model="mixtral-8x7b-32768")  # Replace with the correct Groq model
Settings.llm = llm
Settings.chunk_size = 128

graph_store = SimpleGraphStore()
storage_context = StorageContext.from_defaults(graph_store=graph_store)

# Build the Knowledge Graph Index
index = KnowledgeGraphIndex.from_documents(
    documents=document,  # Ensure it's a list
    max_triplets_per_chunk=2,
    storage_context=storage_context,
)

print("Knowledge Graph Created Successfully with HuggingFace Embedding!")

Knowledge Graph Created Successfully with HuggingFace Embedding!

In [ ]:
index

In [7]:
%pip install llama-index-graph-stores-kuzu

Collecting llama-index-graph-stores-kuzu
  Downloading llama_index_graph_stores_kuzu-0.6.0-py3-none-any.whl.metadata (689 bytes)
Collecting kuzu<0.8.0,>=0.7.0 (from llama-index-graph-stores-kuzu)
  Downloading kuzu-0.7.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.7 kB)
Requirement already satisfied: llama-index-core<0.13.0,>=0.12.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-graph-stores-kuzu) (0.12.15)
Requirement already satisfied: PyYAML>=6.0.1 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (6.0.2)
Requirement already satisfied: SQLAlchemy>=1.4.49 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy[asyncio]>=1.4.49->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (2.0.37)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.6 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (3.11.11)
Requirement already satisfied: dataclasses-json in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (0.6.7)
Requirement already satisfied: deprecated>=1.2.9.3 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (1.2.18)
Requirement already satisfied: dirtyjson<2.0.0,>=1.0.8 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (1.0.8)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (1.2.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (2024.10.0)
Requirement already satisfied: httpx in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (0.28.1)
Requirement already satisfied: nest-asyncio<2.0.0,>=1.5.8 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (1.6.0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (3.4.2)
Requirement already satisfied: nltk>3.8.1 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (1.26.4)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (11.1.0)
Requirement already satisfied: pydantic>=2.8.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (2.10.6)
Requirement already satisfied: requests>=2.31.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (2.32.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.2.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (9.0.0)
Requirement already satisfied: tiktoken>=0.3.3 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (0.8.0)
Requirement already satisfied: tqdm<5.0.0,>=4.66.1 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (4.67.1)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (4.12.2)
Requirement already satisfied: typing-inspect>=0.8.0 in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (0.9.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (1.17.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (1.18.3)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (8.1.8)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk>3.8.1->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (2024.11.6)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.8.0->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.8.0->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (2.27.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31.0->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31.0->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31.0->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31.0->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (2024.12.14)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy>=1.4.49->SQLAlchemy[asyncio]>=1.4.49->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (3.1.1)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from typing-inspect>=0.8.0->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (1.0.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.11/dist-packages (from dataclasses-json->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (3.26.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (3.7.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (0.14.0)
Requirement already satisfied: packaging>=17.0 in /usr/local/lib/python3.11/dist-packages (from marshmallow<4.0.0,>=3.18.0->dataclasses-json->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (24.2)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx->llama-index-core<0.13.0,>=0.12.0->llama-index-graph-stores-kuzu) (1.3.1)
Downloading llama_index_graph_stores_kuzu-0.6.0-py3-none-any.whl (10 kB)
Downloading kuzu-0.7.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 86.0 MB/s eta 0:00:00
Installing collected packages: kuzu, llama-index-graph-stores-kuzu
Successfully installed kuzu-0.7.1 llama-index-graph-stores-kuzu-0.6.0

In [8]:
import kuzu

db = kuzu.Database("test1")

In [11]:
from llama_index.graph_stores.kuzu import KuzuGraphStore

graph_store = KuzuGraphStore(db)
storage_context = StorageContext.from_defaults(graph_store=graph_store)

In [18]:
csv_text = fd.to_string(index=False)

# Create a list of Document objects
document = [Document(text=csv_text)]  # Wrap in a list

# Use HuggingFace's embedding model (change model_name if needed)
embedding_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")

# Set the embedding model
Settings.embed_model = embedding_model

# Initialize Groq LLM
llm = Groq(model="mixtral-8x7b-32768")  # Replace with the correct Groq model
Settings.llm = llm
Settings.chunk_size = 128


# Build the Knowledge Graph Index
index = KnowledgeGraphIndex.from_documents(
    documents=document,  # Ensure it's a list
    max_triplets_per_chunk=2,
    storage_context=storage_context,
)

print("Knowledge Graph Created Successfully with HuggingFace Embedding!")

Knowledge Graph Created Successfully with HuggingFace Embedding!

In [ ]:
#Loading the Constructed knowledge graph, so that it saves recomputation
temp_index = KnowledgeGraphIndex(nodes=[], storage_context=storage_context)

<ipython-input-44-b81520c9687e>:1: DeprecationWarning: Call to deprecated class KnowledgeGraphIndex. (The KnowledgeGraphIndex class has been deprecated. Please use the new PropertyGraphIndex class instead. If a certain graph store integration is missing in the new class, please open an issue on the GitHub repository or contribute it!) -- Deprecated since version 0.10.53.
  temp_index = KnowledgeGraphIndex(nodes=[], storage_context=storage_context)

### Storing the Knowledge Graph

In [19]:
import networkx as nx

# Assuming `index` is your KnowledgeGraphIndex instance
# Convert the knowledge graph to a NetworkX graph
nx_graph = index.get_networkx_graph()

# Write the NetworkX graph to a GraphML file
nx.write_graphml(nx_graph, "knowledge_graph_symptoms.graphml")

print("Knowledge graph has been successfully exported to 'knowledge_graph.graphml'.")

Knowledge graph has been successfully exported to 'knowledge_graph.graphml'.

In [20]:
import networkx as nx

# Read the GraphML file
graph = nx.read_graphml("knowledge_graph_symptoms.graphml")

# Display the nodes
print("Nodes in the graph:")
for node in graph.nodes(data=True):
    print(node)

# Display the edges
print("\nEdges in the graph:")
for edge in graph.edges(data=True):
    print(edge)

Nodes in the graph:
('Fungal infection', {})
('Dischromic patches', {})
('Skin rash', {})
('Itching', {})
('Nodal skin eruptions', {})
('Drug reaction', {})
('Allergy', {})
('Chronic cholestasis', {})
('Peptic ulcer disease', {})
('Jaundice', {})
('Chickenpox', {})
('Liver disease', {})
('Watering from eyes', {})
('Shivering', {})
('Chills', {})
('Continuous sneezing', {})
('Watering\\_from\\_eyes', {})
('Continuous\\_sneezing', {})
('Gerd', {})
('Malaria', {})
('Dengue', {})
('Typhoid', {})
('Tuberculosis', {})
('Common cold', {})
('Pneumonia', {})
('Heart attack', {})
('Chest pain', {})
('Vomiting', {})
('Ulcers on tongue', {})
('Acidity', {})
('Stomach pain', {})
('Cough', {})
('Chest\\_pain', {})
('Ulcers\\_on\\_tongue', {})
('Stomach\\_pain', {})
('Gastroenteritis', {})
('Bronchial asthma', {})
('Paralysis', {})
('Paralysis (brain hemorrhage', {})
('Brain hemorrhage', {})
('Alcoholic hepatitis', {})
('Hypothyroidism', {})
('Hypoglycemia', {})
('Vertigo', {})
('Migraine', {})
('Cervical spondylosis', {})

Edges in the graph:
('Fungal infection', 'Dischromic patches', {'label': 'Has symptoms', 'title': 'Has symptoms'})
('Fungal infection', 'Skin rash', {'label': 'Has symptoms', 'title': 'Has symptoms'})
('Fungal infection', 'Itching', {'label': 'Has symptoms', 'title': 'Has symptoms'})
('Fungal infection', 'Nodal skin eruptions', {'label': 'Has symptoms', 'title': 'Has symptoms'})
('Skin rash', 'Drug reaction', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Itching', 'Allergy', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Itching', 'Chronic cholestasis', {'label': 'Has symptoms', 'title': 'Has symptoms'})
('Itching', 'Drug reaction', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Itching', 'Peptic ulcer disease', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Itching', 'Jaundice', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Itching', 'Chickenpox', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Itching', 'Liver disease', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Drug reaction', 'Cough', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Allergy', 'Watering from eyes', {'label': 'Has symptoms', 'title': 'Has symptoms'})
('Allergy', 'Shivering', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Allergy', 'Chills', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Allergy', 'Continuous sneezing', {'label': 'Has symptoms', 'title': 'Has symptoms'})
('Allergy', 'Watering\\_from\\_eyes', {'label': 'Has symptom', 'title': 'Has symptom'})
('Allergy', 'Continuous\\_sneezing', {'label': 'Has symptom', 'title': 'Has symptom'})
('Chronic cholestasis', 'Shivering', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Chronic cholestasis', 'Vomiting', {'label': 'Has symptoms', 'title': 'Has symptoms'})
('Peptic ulcer disease', 'Vomiting', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Peptic ulcer disease', 'Ulcers on tongue', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Peptic ulcer disease', 'Acidity', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Peptic ulcer disease', 'Stomach pain', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Peptic ulcer disease', 'Cough', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Jaundice', 'Vomiting', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Jaundice', 'Cough', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Shivering', 'Gerd', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Chills', 'Gerd', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Chills', 'Malaria', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Chills', 'Dengue', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Chills', 'Typhoid', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Chills', 'Tuberculosis', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Chills', 'Common cold', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Chills', 'Pneumonia', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Chills', 'Heart attack', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Continuous sneezing', 'Common cold', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Gerd', 'Chest pain', {'label': 'Has symptoms', 'title': 'Has symptoms'})
('Gerd', 'Vomiting', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Gerd', 'Ulcers on tongue', {'label': 'Has symptoms', 'title': 'Has symptoms'})
('Gerd', 'Acidity', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Gerd', 'Stomach pain', {'label': 'Has symptoms', 'title': 'Has symptoms'})
('Gerd', 'Cough', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Gerd', 'Chest\\_pain', {'label': 'Has symptom', 'title': 'Has symptom'})
('Gerd', 'Ulcers\\_on\\_tongue', {'label': 'Has symptom', 'title': 'Has symptom'})
('Gerd', 'Stomach\\_pain', {'label': 'Has symptom', 'title': 'Has symptom'})
('Malaria', 'Vomiting', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Dengue', 'Vomiting', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Typhoid', 'Vomiting', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Tuberculosis', 'Chest pain', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Tuberculosis', 'Vomiting', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Tuberculosis', 'Cough', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Common cold', 'Chest pain', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Common cold', 'Vomiting', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Common cold', 'Cough', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Pneumonia', 'Chest pain', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Pneumonia', 'Vomiting', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Pneumonia', 'Cough', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Heart attack', 'Vomiting', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Heart attack', 'Cough', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Vomiting', 'Gastroenteritis', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Vomiting', 'Bronchial asthma', {'label': 'Is a symptom of', 'title': 'Is a symptom of'})
('Vomiting', 'Paralysis', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Vomiting', 'Paralysis (brain hemorrhage', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Vomiting', 'Brain hemorrhage', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Vomiting', 'Alcoholic hepatitis', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Vomiting', 'Hypothyroidism', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Vomiting', 'Hypoglycemia', {'label': 'Is a symptom of', 'title': 'Is a symptom of'})
('Vomiting', 'Vertigo', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Acidity', 'Stomach\\_pain', {'label': 'Causes', 'title': 'Causes'})
('Acidity', 'Migraine', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Cough', 'Bronchial asthma', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Cough', 'Cervical spondylosis', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Cough', 'Paralysis (brain hemorrhage', {'label': 'Is symptom of', 'title': 'Is symptom of'})

In [21]:
# Assuming `index` is your KnowledgeGraphIndex instance
temp_graph_store = index.graph_store

In [ ]:
## create graph
from pyvis.network import Network

g = index.get_networkx_graph()
net = Network(notebook=True, cdn_resources="in_line", directed=True)
net.from_nx(g)
net.show("kuzugraph_draw.html")

kuzugraph_draw.html

### Accessing the Attributes of the Constructed Knowledge Graph

In [ ]:
from llama_index.graph_stores.kuzu import KuzuGraphStore
import networkx as nx

# Assuming `index` is your KnowledgeGraphIndex instance
# Convert the knowledge graph to a NetworkX graph
nx_graph = index.get_networkx_graph()

# Iterate over nodes
print("Nodes in the Knowledge Graph:")
for node in nx_graph.nodes(data=True):
    print(node)

# Iterate over edges
print("\nEdges in the Knowledge Graph:")
for edge in nx_graph.edges(data=True):
    print(edge)

Nodes in the Knowledge Graph:
('Fungal infection', {})
('Dischromic patches', {})
('Skin rash', {})
('Itching', {})
('Nodal skin eruptions', {})
('Drug reaction', {})
('Allergy', {})
('Chronic cholestasis', {})
('Peptic ulcer disease', {})
('Jaundice', {})
('Malaria', {})
('Chickenpox', {})
('Liver disease', {})
('Watering from eyes', {})
('Shivering', {})
('Chills', {})
('Continuous sneezing', {})
('Watering\\_from\\_eyes', {})
('Continuous\\_sneezing', {})
('Gerd', {})
('Dengue', {})
('Typhoid', {})
('Tuberculosis', {})
('Common cold', {})
('Pneumonia', {})
('Chest pain', {})
('Vomiting', {})
('Ulcers on tongue', {})
('Acidity', {})
('Stomach pain', {})
('Cough', {})
('Chest\\_pain', {})
('Ulcers\\_on\\_tongue', {})
('Stomach\\_pain', {})
('Gastroenteritis', {})
('Bronchial asthma', {})
('Paralysis', {})
('Paralysis (brain hemorrhage', {})
('Brain hemorrhage', {})
('Alcoholic hepatitis', {})
('Heart attack', {})
('Hypothyroidism', {})
('Hypoglycemia', {})
('Vertigo', {})
('Migraine', {})
('Cervical spondylosis', {})
('Dimorphic hemmorhoids', {})
('Loss of appetite', {})

Edges in the Knowledge Graph:
('Fungal infection', 'Dischromic patches', {'label': 'Has symptoms', 'title': 'Has symptoms'})
('Fungal infection', 'Skin rash', {'label': 'Has symptoms', 'title': 'Has symptoms'})
('Fungal infection', 'Itching', {'label': 'Has symptoms', 'title': 'Has symptoms'})
('Fungal infection', 'Nodal skin eruptions', {'label': 'Has symptoms', 'title': 'Has symptoms'})
('Skin rash', 'Drug reaction', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Itching', 'Allergy', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Itching', 'Chronic cholestasis', {'label': 'Has symptoms', 'title': 'Has symptoms'})
('Itching', 'Drug reaction', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Itching', 'Peptic ulcer disease', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Itching', 'Jaundice', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Itching', 'Malaria', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Itching', 'Chickenpox', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Itching', 'Liver disease', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Drug reaction', 'Cough', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Allergy', 'Watering from eyes', {'label': 'Has symptoms', 'title': 'Has symptoms'})
('Allergy', 'Shivering', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Allergy', 'Chills', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Allergy', 'Continuous sneezing', {'label': 'Has symptoms', 'title': 'Has symptoms'})
('Allergy', 'Watering\\_from\\_eyes', {'label': 'Has symptom', 'title': 'Has symptom'})
('Allergy', 'Continuous\\_sneezing', {'label': 'Has symptom', 'title': 'Has symptom'})
('Chronic cholestasis', 'Shivering', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Chronic cholestasis', 'Vomiting', {'label': 'Has symptoms', 'title': 'Has symptoms'})
('Chronic cholestasis', 'Loss of appetite', {'label': 'Has symptoms', 'title': 'Has symptoms'})
('Peptic ulcer disease', 'Vomiting', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Peptic ulcer disease', 'Ulcers on tongue', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Peptic ulcer disease', 'Acidity', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Peptic ulcer disease', 'Stomach pain', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Peptic ulcer disease', 'Cough', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Jaundice', 'Vomiting', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Jaundice', 'Cough', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Malaria', 'Chills', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Malaria', 'Vomiting', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Shivering', 'Gerd', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Chills', 'Gerd', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Chills', 'Dengue', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Chills', 'Typhoid', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Chills', 'Tuberculosis', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Chills', 'Common cold', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Chills', 'Pneumonia', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Gerd', 'Chest pain', {'label': 'Has symptoms', 'title': 'Has symptoms'})
('Gerd', 'Vomiting', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Gerd', 'Ulcers on tongue', {'label': 'Has symptoms', 'title': 'Has symptoms'})
('Gerd', 'Acidity', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Gerd', 'Stomach pain', {'label': 'Has symptoms', 'title': 'Has symptoms'})
('Gerd', 'Cough', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Gerd', 'Chest\\_pain', {'label': 'Has symptom', 'title': 'Has symptom'})
('Gerd', 'Ulcers\\_on\\_tongue', {'label': 'Has symptom', 'title': 'Has symptom'})
('Gerd', 'Stomach\\_pain', {'label': 'Has symptom', 'title': 'Has symptom'})
('Dengue', 'Vomiting', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Typhoid', 'Vomiting', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Tuberculosis', 'Chest pain', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Tuberculosis', 'Vomiting', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Tuberculosis', 'Cough', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Common cold', 'Chest pain', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Common cold', 'Vomiting', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Common cold', 'Cough', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Pneumonia', 'Chest pain', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Pneumonia', 'Cough', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Vomiting', 'Gastroenteritis', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Vomiting', 'Bronchial asthma', {'label': 'Is a symptom of', 'title': 'Is a symptom of'})
('Vomiting', 'Paralysis', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Vomiting', 'Paralysis (brain hemorrhage', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Vomiting', 'Brain hemorrhage', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Vomiting', 'Alcoholic hepatitis', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Vomiting', 'Heart attack', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Vomiting', 'Hypothyroidism', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Vomiting', 'Hypoglycemia', {'label': 'Is a symptom of', 'title': 'Is a symptom of'})
('Vomiting', 'Vertigo', {'label': 'Is a symptom of', 'title': 'Is a symptom of'})
('Acidity', 'Stomach\\_pain', {'label': 'Causes', 'title': 'Causes'})
('Acidity', 'Migraine', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Cough', 'Bronchial asthma', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Cough', 'Cervical spondylosis', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Cough', 'Paralysis (brain hemorrhage', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Cough', 'Dimorphic hemmorhoids', {'label': 'Is symptom of', 'title': 'Is symptom of'})
('Cough', 'Heart attack', {'label': 'Is symptom of', 'title': 'Is symptom of'})

### Testing Out Tavily Search

In [22]:
%pip install llama-index chromadb phidata tavily

Requirement already satisfied: llama-index in /usr/local/lib/python3.11/dist-packages (0.12.15)
Requirement already satisfied: chromadb in /usr/local/lib/python3.11/dist-packages (0.6.3)
Collecting phidata
  Downloading phidata-2.7.10-py3-none-any.whl.metadata (38 kB)
ERROR: Could not find a version that satisfies the requirement tavily (from versions: none)
ERROR: No matching distribution found for tavily

In [23]:
%pip install -qU "langchain-community>=0.2.11" tavily-python

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 56.5 MB/s eta 0:00:00

In [24]:
os.environ['TAVILY_API_KEY'] = userdata.get('tavily_api')

In [25]:
from tavily import TavilyClient

# Step 1. Instantiating your TavilyClient
tavily_client = TavilyClient()

# Step 2. Executing a simple search query
response = tavily_client.search("What is an Agentic RAG?")

# Step 3. That's it! You've done a Tavily Search!
print(response['results'][2]['content'])

What Is Agentic RAG? Agentic RAG (Agent-based RAG implementation) revolutionizes question answering through an innovative agent-based framework. Unlike traditional approaches that solely rely on large language models (LLMs), agentic RAG employs intelligent agents to adeptly tackle complex questions.

### Creating the Agent

In [26]:
%pip install -U phidata

Collecting phidata
  Using cached phidata-2.7.10-py3-none-any.whl.metadata (38 kB)
Requirement already satisfied: docstring-parser in /usr/local/lib/python3.11/dist-packages (from phidata) (0.16)
Requirement already satisfied: gitpython in /usr/local/lib/python3.11/dist-packages (from phidata) (3.1.44)
Requirement already satisfied: httpx in /usr/local/lib/python3.11/dist-packages (from phidata) (0.28.1)
Requirement already satisfied: pydantic in /usr/local/lib/python3.11/dist-packages (from phidata) (2.10.6)
Requirement already satisfied: pydantic-settings in /usr/local/lib/python3.11/dist-packages (from phidata) (2.7.1)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.11/dist-packages (from phidata) (1.0.1)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from phidata) (6.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from phidata) (13.9.4)
Collecting tomli (from phidata)
  Downloading tomli-2.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Requirement already satisfied: typer in /usr/local/lib/python3.11/dist-packages (from phidata) (0.15.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.11/dist-packages (from phidata) (4.12.2)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from gitpython->phidata) (4.0.12)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx->phidata) (3.7.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx->phidata) (2024.12.14)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx->phidata) (1.0.7)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from httpx->phidata) (3.10)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx->phidata) (0.14.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic->phidata) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic->phidata) (2.27.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->phidata) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->phidata) (2.18.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer->phidata) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer->phidata) (1.5.4)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from gitdb<5,>=4.0.1->gitpython->phidata) (5.0.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->phidata) (0.1.2)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx->phidata) (1.3.1)
Downloading phidata-2.7.10-py3-none-any.whl (716 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 716.9/716.9 kB 31.5 MB/s eta 0:00:00
Downloading tomli-2.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (236 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 236.0/236.0 kB 18.8 MB/s eta 0:00:00
Installing collected packages: tomli, phidata
Successfully installed phidata-2.7.10 tomli-2.2.1

In [27]:
os.environ['GEMINI_API_KEY'] = userdata.get('gemini_api')

In [31]:
os.environ['GOOGLE_API_KEY'] = userdata.get('google_api')

In [29]:
from phi.agent import Agent
from phi.model.google import Gemini
from phi.tools.tavily import TavilyTools
import networkx as nx

# Assuming `index` is your KnowledgeGraphIndex instance
# Convert the knowledge graph to a NetworkX graph
nx_graph = index.get_networkx_graph()

# Initialize a list to store the string representation
graph_str_list = []

# Add nodes to the string representation
graph_str_list.append("Nodes:\n")
for node in nx_graph.nodes(data=True):
    graph_str_list.append(f"{node}\n")

# Add edges to the string representation
graph_str_list.append("\nEdges:\n")
for edge in nx_graph.edges(data=True):
    graph_str_list.append(f"{edge}\n")

# Join the list into a single string
knowledge_graph_text = "".join(graph_str_list)

# Define the AI Agent with system-level knowledge
agent = Agent(
    model=Gemini(id="gemini-1.5-flash"),  # Using Gemini 1.5-flash as the LLM
    tools=[TavilyTools()],  # Web search for medical recommendations
    description="An AI-powered symptom analyzer that provides differential diagnoses and recommended medical actions.",
    instructions=[
        "You are an AI medical assistant that provides users with a preliminary differential diagnosis and recommended medical actions.",
        "You have access to a medical Knowledge Graph that maps symptoms to possible conditions.",
        "You also have access to the Tavily search tool to retrieve real-time medical advice and recommendations.",
        "When given symptoms, follow these steps:",
        "1. Identify possible medical conditions based on the Knowledge Graph.",
        "2. Use Tavily to retrieve recommended actions (e.g., tests, treatments, or doctor consultations).",
        "3. Generate a concise response combining both aspects, ensuring clarity in about 2-3 sentences.",
        "Here is the structured medical Knowledge Graph data you should use:\n\n"
        f"{knowledge_graph_text}\n\n"
        "Use this knowledge before making any diagnoses."
    ],
    markdown=True,
    show_tool_calls=True,
)

print("AI Agent initialized with the knowledge graph.")

AI Agent initialized with the knowledge graph.

In [32]:
def analyze_symptoms(user_input):
    # Generate response using both Knowledge Graph (from system prompt) and Tavily search
    final_response = agent.print_response(user_input)
    return final_response

# Example usage
symptom_input = "I have been experiencing chest pain and shortness of breath."
response = analyze_symptoms(symptom_input)
print(response)

┏━ Message ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                                                  ┃
┃ I have been experiencing chest pain and shortness of breath.                                     ┃
┃                                                                                                  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
┏━ Response (3.6s) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                                                  ┃
┃ Based on your symptoms of chest pain and shortness of breath, possible conditions include a      ┃
┃ heart attack, pneumonia, or a severe case of GERD.  I recommend seeking immediate medical        ┃
┃ attention to get a proper diagnosis and treatment plan.  To get more specific advice, I suggest  ┃
┃ using online search engines for more information on these conditions and their treatments.       ┃
┃                                                                                                  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛None

In [33]:
symptom_input = "I have been feeling fatigued, experiencing frequent headaches, and occasional dizziness."
response = analyze_symptoms(symptom_input)
print(response)

┏━ Message ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                                                  ┃
┃ I have been feeling fatigued, experiencing frequent headaches, and occasional dizziness.         ┃
┃                                                                                                  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
┏━ Response (3.9s) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                                                                  ┃
┃ Based on your symptoms of fatigue, headaches, and dizziness, several conditions are possible,    ┃
┃ including migraine, hypoglycemia, or even cervical spondylosis.  To determine the exact cause, I ┃
┃ recommend consulting a doctor for a proper diagnosis and to discuss appropriate treatment        ┃
┃ options.  Further tests may be necessary to rule out other potential underlying conditions.      ┃
┃                                                                                                  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛None